// This code was auto-generated by Lift Json XSchema - do not edit
package blueeyes.json.xschema {
  import blueeyes.json.JsonParser._
  import blueeyes.json.JsonAST._
  
  
  trait Orderings {
    implicit val XRootOrdering: Ordering[blueeyes.json.xschema.XRoot] = new Ordering[blueeyes.json.xschema.XRoot] {
      def compare(v1: blueeyes.json.xschema.XRoot, v2: blueeyes.json.xschema.XRoot): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = cons(blueeyes.json.xschema.DefaultOrderings.ListOrdering(blueeyes.json.xschema.Orderings.XDefinitionOrdering).compare(v1.definitions, v2.definitions) * 1, cons(blueeyes.json.xschema.DefaultOrderings.ListOrdering(blueeyes.json.xschema.Orderings.XConstantOrdering).compare(v1.constants, v2.constants) * 1, cons(blueeyes.json.xschema.DefaultOrderings.MapOrdering(blueeyes.json.xschema.DefaultOrderings.StringOrdering, blueeyes.json.xschema.DefaultOrderings.JValueOrdering).compare(v1.properties, v2.properties) * 1, empty)))
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XSchemaOrdering: Ordering[blueeyes.json.xschema.XSchema] = new Ordering[blueeyes.json.xschema.XSchema] {
      def compare(v1: blueeyes.json.xschema.XSchema, v2: blueeyes.json.xschema.XSchema): Int = {
        if (v1 == v2) 0
        else v1 match {
          case x: blueeyes.json.xschema.XDefinition => v2 match {
            case y: blueeyes.json.xschema.XDefinition => blueeyes.json.xschema.Orderings.XDefinitionOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XReference => -1
            case y: blueeyes.json.xschema.XField => -1
            case y: blueeyes.json.xschema.XConstant => -1
          }
          case x: blueeyes.json.xschema.XReference => v2 match {
            case y: blueeyes.json.xschema.XDefinition => 1
            case y: blueeyes.json.xschema.XReference => blueeyes.json.xschema.Orderings.XReferenceOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XField => -1
            case y: blueeyes.json.xschema.XConstant => -1
          }
          case x: blueeyes.json.xschema.XField => v2 match {
            case y: blueeyes.json.xschema.XDefinition => 1
            case y: blueeyes.json.xschema.XReference => 1
            case y: blueeyes.json.xschema.XField => blueeyes.json.xschema.Orderings.XFieldOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XConstant => -1
          }
          case x: blueeyes.json.xschema.XConstant => v2 match {
            case y: blueeyes.json.xschema.XDefinition => 1
            case y: blueeyes.json.xschema.XReference => 1
            case y: blueeyes.json.xschema.XField => 1
            case y: blueeyes.json.xschema.XConstant => blueeyes.json.xschema.Orderings.XConstantOrdering.compare(x, y)
          }
        }
      }
    }
    case class OrderedXSchema(v1: blueeyes.json.xschema.XSchema) extends Ordered[blueeyes.json.xschema.XSchema] {
      def compare(v2: blueeyes.json.xschema.XSchema): Int = XSchemaOrdering.compare(v1, v2)
    }
    implicit def XSchemaToOrderedXSchema(v: blueeyes.json.xschema.XSchema) = OrderedXSchema(v)
    
    implicit val XReferenceOrdering: Ordering[blueeyes.json.xschema.XReference] = new Ordering[blueeyes.json.xschema.XReference] {
      def compare(v1: blueeyes.json.xschema.XReference, v2: blueeyes.json.xschema.XReference): Int = {
        if (v1 == v2) 0
        else v1 match {
          case x: blueeyes.json.xschema.XPrimitiveRef => v2 match {
            case y: blueeyes.json.xschema.XPrimitiveRef => blueeyes.json.xschema.Orderings.XPrimitiveRefOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XContainerRef => -1
            case y: blueeyes.json.xschema.XDefinitionRef => -1
          }
          case x: blueeyes.json.xschema.XContainerRef => v2 match {
            case y: blueeyes.json.xschema.XPrimitiveRef => 1
            case y: blueeyes.json.xschema.XContainerRef => blueeyes.json.xschema.Orderings.XContainerRefOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XDefinitionRef => -1
          }
          case x: blueeyes.json.xschema.XDefinitionRef => v2 match {
            case y: blueeyes.json.xschema.XPrimitiveRef => 1
            case y: blueeyes.json.xschema.XContainerRef => 1
            case y: blueeyes.json.xschema.XDefinitionRef => blueeyes.json.xschema.Orderings.XDefinitionRefOrdering.compare(x, y)
          }
        }
      }
    }
    case class OrderedXReference(v1: blueeyes.json.xschema.XReference) extends Ordered[blueeyes.json.xschema.XReference] {
      def compare(v2: blueeyes.json.xschema.XReference): Int = XReferenceOrdering.compare(v1, v2)
    }
    implicit def XReferenceToOrderedXReference(v: blueeyes.json.xschema.XReference) = OrderedXReference(v)
    
    implicit val XPrimitiveRefOrdering: Ordering[blueeyes.json.xschema.XPrimitiveRef] = new Ordering[blueeyes.json.xschema.XPrimitiveRef] {
      def compare(v1: blueeyes.json.xschema.XPrimitiveRef, v2: blueeyes.json.xschema.XPrimitiveRef): Int = {
        if (v1 == v2) 0
        else v1 match {
          case x: blueeyes.json.xschema.XBoolean.type => v2 match {
            case y: blueeyes.json.xschema.XBoolean.type => blueeyes.json.xschema.Orderings.XBooleanOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XInt.type => -1
            case y: blueeyes.json.xschema.XLong.type => -1
            case y: blueeyes.json.xschema.XFloat.type => -1
            case y: blueeyes.json.xschema.XDouble.type => -1
            case y: blueeyes.json.xschema.XString.type => -1
            case y: blueeyes.json.xschema.XJSON.type => -1
            case y: blueeyes.json.xschema.XDate.type => -1
          }
          case x: blueeyes.json.xschema.XInt.type => v2 match {
            case y: blueeyes.json.xschema.XBoolean.type => 1
            case y: blueeyes.json.xschema.XInt.type => blueeyes.json.xschema.Orderings.XIntOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XLong.type => -1
            case y: blueeyes.json.xschema.XFloat.type => -1
            case y: blueeyes.json.xschema.XDouble.type => -1
            case y: blueeyes.json.xschema.XString.type => -1
            case y: blueeyes.json.xschema.XJSON.type => -1
            case y: blueeyes.json.xschema.XDate.type => -1
          }
          case x: blueeyes.json.xschema.XLong.type => v2 match {
            case y: blueeyes.json.xschema.XBoolean.type => 1
            case y: blueeyes.json.xschema.XInt.type => 1
            case y: blueeyes.json.xschema.XLong.type => blueeyes.json.xschema.Orderings.XLongOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XFloat.type => -1
            case y: blueeyes.json.xschema.XDouble.type => -1
            case y: blueeyes.json.xschema.XString.type => -1
            case y: blueeyes.json.xschema.XJSON.type => -1
            case y: blueeyes.json.xschema.XDate.type => -1
          }
          case x: blueeyes.json.xschema.XFloat.type => v2 match {
            case y: blueeyes.json.xschema.XBoolean.type => 1
            case y: blueeyes.json.xschema.XInt.type => 1
            case y: blueeyes.json.xschema.XLong.type => 1
            case y: blueeyes.json.xschema.XFloat.type => blueeyes.json.xschema.Orderings.XFloatOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XDouble.type => -1
            case y: blueeyes.json.xschema.XString.type => -1
            case y: blueeyes.json.xschema.XJSON.type => -1
            case y: blueeyes.json.xschema.XDate.type => -1
          }
          case x: blueeyes.json.xschema.XDouble.type => v2 match {
            case y: blueeyes.json.xschema.XBoolean.type => 1
            case y: blueeyes.json.xschema.XInt.type => 1
            case y: blueeyes.json.xschema.XLong.type => 1
            case y: blueeyes.json.xschema.XFloat.type => 1
            case y: blueeyes.json.xschema.XDouble.type => blueeyes.json.xschema.Orderings.XDoubleOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XString.type => -1
            case y: blueeyes.json.xschema.XJSON.type => -1
            case y: blueeyes.json.xschema.XDate.type => -1
          }
          case x: blueeyes.json.xschema.XString.type => v2 match {
            case y: blueeyes.json.xschema.XBoolean.type => 1
            case y: blueeyes.json.xschema.XInt.type => 1
            case y: blueeyes.json.xschema.XLong.type => 1
            case y: blueeyes.json.xschema.XFloat.type => 1
            case y: blueeyes.json.xschema.XDouble.type => 1
            case y: blueeyes.json.xschema.XString.type => blueeyes.json.xschema.Orderings.XStringOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XJSON.type => -1
            case y: blueeyes.json.xschema.XDate.type => -1
          }
          case x: blueeyes.json.xschema.XJSON.type => v2 match {
            case y: blueeyes.json.xschema.XBoolean.type => 1
            case y: blueeyes.json.xschema.XInt.type => 1
            case y: blueeyes.json.xschema.XLong.type => 1
            case y: blueeyes.json.xschema.XFloat.type => 1
            case y: blueeyes.json.xschema.XDouble.type => 1
            case y: blueeyes.json.xschema.XString.type => 1
            case y: blueeyes.json.xschema.XJSON.type => blueeyes.json.xschema.Orderings.XJSONOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XDate.type => -1
          }
          case x: blueeyes.json.xschema.XDate.type => v2 match {
            case y: blueeyes.json.xschema.XBoolean.type => 1
            case y: blueeyes.json.xschema.XInt.type => 1
            case y: blueeyes.json.xschema.XLong.type => 1
            case y: blueeyes.json.xschema.XFloat.type => 1
            case y: blueeyes.json.xschema.XDouble.type => 1
            case y: blueeyes.json.xschema.XString.type => 1
            case y: blueeyes.json.xschema.XJSON.type => 1
            case y: blueeyes.json.xschema.XDate.type => blueeyes.json.xschema.Orderings.XDateOrdering.compare(x, y)
          }
        }
      }
    }
    case class OrderedXPrimitiveRef(v1: blueeyes.json.xschema.XPrimitiveRef) extends Ordered[blueeyes.json.xschema.XPrimitiveRef] {
      def compare(v2: blueeyes.json.xschema.XPrimitiveRef): Int = XPrimitiveRefOrdering.compare(v1, v2)
    }
    implicit def XPrimitiveRefToOrderedXPrimitiveRef(v: blueeyes.json.xschema.XPrimitiveRef) = OrderedXPrimitiveRef(v)
    
    implicit val XContainerRefOrdering: Ordering[blueeyes.json.xschema.XContainerRef] = new Ordering[blueeyes.json.xschema.XContainerRef] {
      def compare(v1: blueeyes.json.xschema.XContainerRef, v2: blueeyes.json.xschema.XContainerRef): Int = {
        if (v1 == v2) 0
        else v1 match {
          case x: blueeyes.json.xschema.XCollection => v2 match {
            case y: blueeyes.json.xschema.XCollection => blueeyes.json.xschema.Orderings.XCollectionOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XMap => -1
            case y: blueeyes.json.xschema.XOptional => -1
            case y: blueeyes.json.xschema.XTuple => -1
          }
          case x: blueeyes.json.xschema.XMap => v2 match {
            case y: blueeyes.json.xschema.XCollection => 1
            case y: blueeyes.json.xschema.XMap => blueeyes.json.xschema.Orderings.XMapOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XOptional => -1
            case y: blueeyes.json.xschema.XTuple => -1
          }
          case x: blueeyes.json.xschema.XOptional => v2 match {
            case y: blueeyes.json.xschema.XCollection => 1
            case y: blueeyes.json.xschema.XMap => 1
            case y: blueeyes.json.xschema.XOptional => blueeyes.json.xschema.Orderings.XOptionalOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XTuple => -1
          }
          case x: blueeyes.json.xschema.XTuple => v2 match {
            case y: blueeyes.json.xschema.XCollection => 1
            case y: blueeyes.json.xschema.XMap => 1
            case y: blueeyes.json.xschema.XOptional => 1
            case y: blueeyes.json.xschema.XTuple => blueeyes.json.xschema.Orderings.XTupleOrdering.compare(x, y)
          }
        }
      }
    }
    case class OrderedXContainerRef(v1: blueeyes.json.xschema.XContainerRef) extends Ordered[blueeyes.json.xschema.XContainerRef] {
      def compare(v2: blueeyes.json.xschema.XContainerRef): Int = XContainerRefOrdering.compare(v1, v2)
    }
    implicit def XContainerRefToOrderedXContainerRef(v: blueeyes.json.xschema.XContainerRef) = OrderedXContainerRef(v)
    
    implicit val XDefinitionRefOrdering: Ordering[blueeyes.json.xschema.XDefinitionRef] = new Ordering[blueeyes.json.xschema.XDefinitionRef] {
      def compare(v1: blueeyes.json.xschema.XDefinitionRef, v2: blueeyes.json.xschema.XDefinitionRef): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = cons(blueeyes.json.xschema.DefaultOrderings.StringOrdering.compare(v1.name, v2.name) * 1, cons(blueeyes.json.xschema.DefaultOrderings.StringOrdering.compare(v1.namespace, v2.namespace) * 1, empty))
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XBooleanOrdering: Ordering[blueeyes.json.xschema.XBoolean.type] = new Ordering[blueeyes.json.xschema.XBoolean.type] {
      def compare(v1: blueeyes.json.xschema.XBoolean.type, v2: blueeyes.json.xschema.XBoolean.type): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = empty
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XIntOrdering: Ordering[blueeyes.json.xschema.XInt.type] = new Ordering[blueeyes.json.xschema.XInt.type] {
      def compare(v1: blueeyes.json.xschema.XInt.type, v2: blueeyes.json.xschema.XInt.type): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = empty
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XLongOrdering: Ordering[blueeyes.json.xschema.XLong.type] = new Ordering[blueeyes.json.xschema.XLong.type] {
      def compare(v1: blueeyes.json.xschema.XLong.type, v2: blueeyes.json.xschema.XLong.type): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = empty
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XFloatOrdering: Ordering[blueeyes.json.xschema.XFloat.type] = new Ordering[blueeyes.json.xschema.XFloat.type] {
      def compare(v1: blueeyes.json.xschema.XFloat.type, v2: blueeyes.json.xschema.XFloat.type): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = empty
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XDoubleOrdering: Ordering[blueeyes.json.xschema.XDouble.type] = new Ordering[blueeyes.json.xschema.XDouble.type] {
      def compare(v1: blueeyes.json.xschema.XDouble.type, v2: blueeyes.json.xschema.XDouble.type): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = empty
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XStringOrdering: Ordering[blueeyes.json.xschema.XString.type] = new Ordering[blueeyes.json.xschema.XString.type] {
      def compare(v1: blueeyes.json.xschema.XString.type, v2: blueeyes.json.xschema.XString.type): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = empty
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XJSONOrdering: Ordering[blueeyes.json.xschema.XJSON.type] = new Ordering[blueeyes.json.xschema.XJSON.type] {
      def compare(v1: blueeyes.json.xschema.XJSON.type, v2: blueeyes.json.xschema.XJSON.type): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = empty
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XDateOrdering: Ordering[blueeyes.json.xschema.XDate.type] = new Ordering[blueeyes.json.xschema.XDate.type] {
      def compare(v1: blueeyes.json.xschema.XDate.type, v2: blueeyes.json.xschema.XDate.type): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = empty
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XCollectionOrdering: Ordering[blueeyes.json.xschema.XCollection] = new Ordering[blueeyes.json.xschema.XCollection] {
      def compare(v1: blueeyes.json.xschema.XCollection, v2: blueeyes.json.xschema.XCollection): Int = {
        if (v1 == v2) 0
        else v1 match {
          case x: blueeyes.json.xschema.XList => v2 match {
            case y: blueeyes.json.xschema.XList => blueeyes.json.xschema.Orderings.XListOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XSet => -1
            case y: blueeyes.json.xschema.XArray => -1
          }
          case x: blueeyes.json.xschema.XSet => v2 match {
            case y: blueeyes.json.xschema.XList => 1
            case y: blueeyes.json.xschema.XSet => blueeyes.json.xschema.Orderings.XSetOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XArray => -1
          }
          case x: blueeyes.json.xschema.XArray => v2 match {
            case y: blueeyes.json.xschema.XList => 1
            case y: blueeyes.json.xschema.XSet => 1
            case y: blueeyes.json.xschema.XArray => blueeyes.json.xschema.Orderings.XArrayOrdering.compare(x, y)
          }
        }
      }
    }
    case class OrderedXCollection(v1: blueeyes.json.xschema.XCollection) extends Ordered[blueeyes.json.xschema.XCollection] {
      def compare(v2: blueeyes.json.xschema.XCollection): Int = XCollectionOrdering.compare(v1, v2)
    }
    implicit def XCollectionToOrderedXCollection(v: blueeyes.json.xschema.XCollection) = OrderedXCollection(v)
    
    implicit val XListOrdering: Ordering[blueeyes.json.xschema.XList] = new Ordering[blueeyes.json.xschema.XList] {
      def compare(v1: blueeyes.json.xschema.XList, v2: blueeyes.json.xschema.XList): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = cons(blueeyes.json.xschema.Orderings.XReferenceOrdering.compare(v1.elementType, v2.elementType) * 1, empty)
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XSetOrdering: Ordering[blueeyes.json.xschema.XSet] = new Ordering[blueeyes.json.xschema.XSet] {
      def compare(v1: blueeyes.json.xschema.XSet, v2: blueeyes.json.xschema.XSet): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = cons(blueeyes.json.xschema.Orderings.XReferenceOrdering.compare(v1.elementType, v2.elementType) * 1, empty)
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XArrayOrdering: Ordering[blueeyes.json.xschema.XArray] = new Ordering[blueeyes.json.xschema.XArray] {
      def compare(v1: blueeyes.json.xschema.XArray, v2: blueeyes.json.xschema.XArray): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = cons(blueeyes.json.xschema.Orderings.XReferenceOrdering.compare(v1.elementType, v2.elementType) * 1, empty)
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XMapOrdering: Ordering[blueeyes.json.xschema.XMap] = new Ordering[blueeyes.json.xschema.XMap] {
      def compare(v1: blueeyes.json.xschema.XMap, v2: blueeyes.json.xschema.XMap): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = cons(blueeyes.json.xschema.Orderings.XReferenceOrdering.compare(v1.keyType, v2.keyType) * 1, cons(blueeyes.json.xschema.Orderings.XReferenceOrdering.compare(v1.valueType, v2.valueType) * 1, empty))
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XOptionalOrdering: Ordering[blueeyes.json.xschema.XOptional] = new Ordering[blueeyes.json.xschema.XOptional] {
      def compare(v1: blueeyes.json.xschema.XOptional, v2: blueeyes.json.xschema.XOptional): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = cons(blueeyes.json.xschema.Orderings.XReferenceOrdering.compare(v1.optionalType, v2.optionalType) * 1, empty)
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XTupleOrdering: Ordering[blueeyes.json.xschema.XTuple] = new Ordering[blueeyes.json.xschema.XTuple] {
      def compare(v1: blueeyes.json.xschema.XTuple, v2: blueeyes.json.xschema.XTuple): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = cons(blueeyes.json.xschema.DefaultOrderings.ListOrdering(blueeyes.json.xschema.Orderings.XReferenceOrdering).compare(v1.types, v2.types) * 1, empty)
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XDefinitionOrdering: Ordering[blueeyes.json.xschema.XDefinition] = new Ordering[blueeyes.json.xschema.XDefinition] {
      def compare(v1: blueeyes.json.xschema.XDefinition, v2: blueeyes.json.xschema.XDefinition): Int = {
        if (v1 == v2) 0
        else v1 match {
          case x: blueeyes.json.xschema.XProduct => v2 match {
            case y: blueeyes.json.xschema.XProduct => blueeyes.json.xschema.Orderings.XProductOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XMultitype => -1
          }
          case x: blueeyes.json.xschema.XMultitype => v2 match {
            case y: blueeyes.json.xschema.XProduct => 1
            case y: blueeyes.json.xschema.XMultitype => blueeyes.json.xschema.Orderings.XMultitypeOrdering.compare(x, y)
          }
        }
      }
    }
    case class OrderedXDefinition(v1: blueeyes.json.xschema.XDefinition) extends Ordered[blueeyes.json.xschema.XDefinition] {
      def compare(v2: blueeyes.json.xschema.XDefinition): Int = XDefinitionOrdering.compare(v1, v2)
    }
    implicit def XDefinitionToOrderedXDefinition(v: blueeyes.json.xschema.XDefinition) = OrderedXDefinition(v)
    
    implicit val XMultitypeOrdering: Ordering[blueeyes.json.xschema.XMultitype] = new Ordering[blueeyes.json.xschema.XMultitype] {
      def compare(v1: blueeyes.json.xschema.XMultitype, v2: blueeyes.json.xschema.XMultitype): Int = {
        if (v1 == v2) 0
        else v1 match {
          case x: blueeyes.json.xschema.XCoproduct => v2 match {
            case y: blueeyes.json.xschema.XCoproduct => blueeyes.json.xschema.Orderings.XCoproductOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XUnion => -1
          }
          case x: blueeyes.json.xschema.XUnion => v2 match {
            case y: blueeyes.json.xschema.XCoproduct => 1
            case y: blueeyes.json.xschema.XUnion => blueeyes.json.xschema.Orderings.XUnionOrdering.compare(x, y)
          }
        }
      }
    }
    case class OrderedXMultitype(v1: blueeyes.json.xschema.XMultitype) extends Ordered[blueeyes.json.xschema.XMultitype] {
      def compare(v2: blueeyes.json.xschema.XMultitype): Int = XMultitypeOrdering.compare(v1, v2)
    }
    implicit def XMultitypeToOrderedXMultitype(v: blueeyes.json.xschema.XMultitype) = OrderedXMultitype(v)
    
    implicit val XFieldOrdering: Ordering[blueeyes.json.xschema.XField] = new Ordering[blueeyes.json.xschema.XField] {
      def compare(v1: blueeyes.json.xschema.XField, v2: blueeyes.json.xschema.XField): Int = {
        if (v1 == v2) 0
        else v1 match {
          case x: blueeyes.json.xschema.XRealField => v2 match {
            case y: blueeyes.json.xschema.XRealField => blueeyes.json.xschema.Orderings.XRealFieldOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XViewField => -1
            case y: blueeyes.json.xschema.XConstantField => -1
          }
          case x: blueeyes.json.xschema.XViewField => v2 match {
            case y: blueeyes.json.xschema.XRealField => 1
            case y: blueeyes.json.xschema.XViewField => blueeyes.json.xschema.Orderings.XViewFieldOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XConstantField => -1
          }
          case x: blueeyes.json.xschema.XConstantField => v2 match {
            case y: blueeyes.json.xschema.XRealField => 1
            case y: blueeyes.json.xschema.XViewField => 1
            case y: blueeyes.json.xschema.XConstantField => blueeyes.json.xschema.Orderings.XConstantFieldOrdering.compare(x, y)
          }
        }
      }
    }
    case class OrderedXField(v1: blueeyes.json.xschema.XField) extends Ordered[blueeyes.json.xschema.XField] {
      def compare(v2: blueeyes.json.xschema.XField): Int = XFieldOrdering.compare(v1, v2)
    }
    implicit def XFieldToOrderedXField(v: blueeyes.json.xschema.XField) = OrderedXField(v)
    
    implicit val XProductOrdering: Ordering[blueeyes.json.xschema.XProduct] = new Ordering[blueeyes.json.xschema.XProduct] {
      def compare(v1: blueeyes.json.xschema.XProduct, v2: blueeyes.json.xschema.XProduct): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = cons(blueeyes.json.xschema.DefaultOrderings.StringOrdering.compare(v1.name, v2.name) * 1, cons(blueeyes.json.xschema.DefaultOrderings.StringOrdering.compare(v1.namespace, v2.namespace) * 1, cons(blueeyes.json.xschema.DefaultOrderings.MapOrdering(blueeyes.json.xschema.DefaultOrderings.StringOrdering, blueeyes.json.xschema.DefaultOrderings.JValueOrdering).compare(v1.properties, v2.properties) * 1, cons(blueeyes.json.xschema.DefaultOrderings.ListOrdering(blueeyes.json.xschema.Orderings.XFieldOrdering).compare(v1.terms, v2.terms) * 1, empty))))
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XCoproductOrdering: Ordering[blueeyes.json.xschema.XCoproduct] = new Ordering[blueeyes.json.xschema.XCoproduct] {
      def compare(v1: blueeyes.json.xschema.XCoproduct, v2: blueeyes.json.xschema.XCoproduct): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = cons(blueeyes.json.xschema.DefaultOrderings.StringOrdering.compare(v1.name, v2.name) * 1, cons(blueeyes.json.xschema.DefaultOrderings.StringOrdering.compare(v1.namespace, v2.namespace) * 1, cons(blueeyes.json.xschema.DefaultOrderings.MapOrdering(blueeyes.json.xschema.DefaultOrderings.StringOrdering, blueeyes.json.xschema.DefaultOrderings.JValueOrdering).compare(v1.properties, v2.properties) * 1, cons(blueeyes.json.xschema.DefaultOrderings.ListOrdering(blueeyes.json.xschema.Orderings.XDefinitionRefOrdering).compare(v1.terms, v2.terms) * 1, cons(blueeyes.json.xschema.DefaultOrderings.JValueOrdering.compare(v1.default, v2.default) * 1, empty)))))
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XUnionOrdering: Ordering[blueeyes.json.xschema.XUnion] = new Ordering[blueeyes.json.xschema.XUnion] {
      def compare(v1: blueeyes.json.xschema.XUnion, v2: blueeyes.json.xschema.XUnion): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = cons(blueeyes.json.xschema.DefaultOrderings.StringOrdering.compare(v1.name, v2.name) * 1, cons(blueeyes.json.xschema.DefaultOrderings.StringOrdering.compare(v1.namespace, v2.namespace) * 1, cons(blueeyes.json.xschema.DefaultOrderings.MapOrdering(blueeyes.json.xschema.DefaultOrderings.StringOrdering, blueeyes.json.xschema.DefaultOrderings.JValueOrdering).compare(v1.properties, v2.properties) * 1, cons(blueeyes.json.xschema.DefaultOrderings.ListOrdering(blueeyes.json.xschema.Orderings.XReferenceOrdering).compare(v1.terms, v2.terms) * 1, cons(blueeyes.json.xschema.DefaultOrderings.JValueOrdering.compare(v1.default, v2.default) * 1, empty)))))
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XConstantOrdering: Ordering[blueeyes.json.xschema.XConstant] = new Ordering[blueeyes.json.xschema.XConstant] {
      def compare(v1: blueeyes.json.xschema.XConstant, v2: blueeyes.json.xschema.XConstant): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = cons(blueeyes.json.xschema.DefaultOrderings.StringOrdering.compare(v1.name, v2.name) * 1, cons(blueeyes.json.xschema.DefaultOrderings.StringOrdering.compare(v1.namespace, v2.namespace) * 1, cons(blueeyes.json.xschema.DefaultOrderings.MapOrdering(blueeyes.json.xschema.DefaultOrderings.StringOrdering, blueeyes.json.xschema.DefaultOrderings.JValueOrdering).compare(v1.properties, v2.properties) * 1, cons(blueeyes.json.xschema.Orderings.XReferenceOrdering.compare(v1.constantType, v2.constantType) * 1, cons(blueeyes.json.xschema.DefaultOrderings.JValueOrdering.compare(v1.default, v2.default) * 1, empty)))))
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XRealFieldOrdering: Ordering[blueeyes.json.xschema.XRealField] = new Ordering[blueeyes.json.xschema.XRealField] {
      def compare(v1: blueeyes.json.xschema.XRealField, v2: blueeyes.json.xschema.XRealField): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = cons(blueeyes.json.xschema.DefaultOrderings.StringOrdering.compare(v1.name, v2.name) * 1, cons(blueeyes.json.xschema.DefaultOrderings.MapOrdering(blueeyes.json.xschema.DefaultOrderings.StringOrdering, blueeyes.json.xschema.DefaultOrderings.JValueOrdering).compare(v1.properties, v2.properties) * 1, cons(blueeyes.json.xschema.Orderings.XReferenceOrdering.compare(v1.fieldType, v2.fieldType) * 1, cons(blueeyes.json.xschema.DefaultOrderings.JValueOrdering.compare(v1.default, v2.default) * 1, cons(blueeyes.json.xschema.Orderings.XOrderOrdering.compare(v1.order, v2.order) * 1, empty)))))
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XViewFieldOrdering: Ordering[blueeyes.json.xschema.XViewField] = new Ordering[blueeyes.json.xschema.XViewField] {
      def compare(v1: blueeyes.json.xschema.XViewField, v2: blueeyes.json.xschema.XViewField): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = cons(blueeyes.json.xschema.DefaultOrderings.StringOrdering.compare(v1.name, v2.name) * 1, cons(blueeyes.json.xschema.DefaultOrderings.MapOrdering(blueeyes.json.xschema.DefaultOrderings.StringOrdering, blueeyes.json.xschema.DefaultOrderings.JValueOrdering).compare(v1.properties, v2.properties) * 1, cons(blueeyes.json.xschema.Orderings.XReferenceOrdering.compare(v1.fieldType, v2.fieldType) * 1, empty)))
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XConstantFieldOrdering: Ordering[blueeyes.json.xschema.XConstantField] = new Ordering[blueeyes.json.xschema.XConstantField] {
      def compare(v1: blueeyes.json.xschema.XConstantField, v2: blueeyes.json.xschema.XConstantField): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = cons(blueeyes.json.xschema.DefaultOrderings.StringOrdering.compare(v1.name, v2.name) * 1, cons(blueeyes.json.xschema.DefaultOrderings.MapOrdering(blueeyes.json.xschema.DefaultOrderings.StringOrdering, blueeyes.json.xschema.DefaultOrderings.JValueOrdering).compare(v1.properties, v2.properties) * 1, cons(blueeyes.json.xschema.Orderings.XReferenceOrdering.compare(v1.fieldType, v2.fieldType) * 1, cons(blueeyes.json.xschema.DefaultOrderings.JValueOrdering.compare(v1.default, v2.default) * 1, empty))))
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XOrderOrdering: Ordering[blueeyes.json.xschema.XOrder] = new Ordering[blueeyes.json.xschema.XOrder] {
      def compare(v1: blueeyes.json.xschema.XOrder, v2: blueeyes.json.xschema.XOrder): Int = {
        if (v1 == v2) 0
        else v1 match {
          case x: blueeyes.json.xschema.XOrderAscending.type => v2 match {
            case y: blueeyes.json.xschema.XOrderAscending.type => blueeyes.json.xschema.Orderings.XOrderAscendingOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XOrderDescending.type => -1
            case y: blueeyes.json.xschema.XOrderIgnore.type => -1
          }
          case x: blueeyes.json.xschema.XOrderDescending.type => v2 match {
            case y: blueeyes.json.xschema.XOrderAscending.type => 1
            case y: blueeyes.json.xschema.XOrderDescending.type => blueeyes.json.xschema.Orderings.XOrderDescendingOrdering.compare(x, y)
            case y: blueeyes.json.xschema.XOrderIgnore.type => -1
          }
          case x: blueeyes.json.xschema.XOrderIgnore.type => v2 match {
            case y: blueeyes.json.xschema.XOrderAscending.type => 1
            case y: blueeyes.json.xschema.XOrderDescending.type => 1
            case y: blueeyes.json.xschema.XOrderIgnore.type => blueeyes.json.xschema.Orderings.XOrderIgnoreOrdering.compare(x, y)
          }
        }
      }
    }
    case class OrderedXOrder(v1: blueeyes.json.xschema.XOrder) extends Ordered[blueeyes.json.xschema.XOrder] {
      def compare(v2: blueeyes.json.xschema.XOrder): Int = XOrderOrdering.compare(v1, v2)
    }
    implicit def XOrderToOrderedXOrder(v: blueeyes.json.xschema.XOrder) = OrderedXOrder(v)
    
    implicit val XOrderAscendingOrdering: Ordering[blueeyes.json.xschema.XOrderAscending.type] = new Ordering[blueeyes.json.xschema.XOrderAscending.type] {
      def compare(v1: blueeyes.json.xschema.XOrderAscending.type, v2: blueeyes.json.xschema.XOrderAscending.type): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = empty
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XOrderDescendingOrdering: Ordering[blueeyes.json.xschema.XOrderDescending.type] = new Ordering[blueeyes.json.xschema.XOrderDescending.type] {
      def compare(v1: blueeyes.json.xschema.XOrderDescending.type, v2: blueeyes.json.xschema.XOrderDescending.type): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = empty
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
    
    implicit val XOrderIgnoreOrdering: Ordering[blueeyes.json.xschema.XOrderIgnore.type] = new Ordering[blueeyes.json.xschema.XOrderIgnore.type] {
      def compare(v1: blueeyes.json.xschema.XOrderIgnore.type, v2: blueeyes.json.xschema.XOrderIgnore.type): Int = {
        import Stream.{cons, empty}
        
        return if (v1 == v2) 0 else {      
          val comparisons = empty
          
          comparisons.dropWhile(_ == 0).append(0 :: Nil).head
        }
      }
    }
  }
  object Orderings extends Orderings
  
  sealed trait XSchema extends Product {
    
  }
  
  sealed trait XReference extends Product with blueeyes.json.xschema.XSchema {
    
  }
  
  sealed trait XPrimitiveRef extends Product with blueeyes.json.xschema.XReference {
    
  }
  
  sealed trait XContainerRef extends Product with blueeyes.json.xschema.XReference {
    
  }
  
  sealed trait XCollection extends Product with blueeyes.json.xschema.XContainerRef {
    def elementType: blueeyes.json.xschema.XReference
  }
  
  sealed trait XDefinition extends Product with blueeyes.json.xschema.XSchema {
    def referenceTo: blueeyes.json.xschema.XDefinitionRef
    def properties: Map[String, blueeyes.json.JsonAST.JValue]
    def namespace: String
    def name: String
  }
  
  sealed trait XMultitype extends Product with blueeyes.json.xschema.XDefinition {
    def referenceTo: blueeyes.json.xschema.XDefinitionRef
    def properties: Map[String, blueeyes.json.JsonAST.JValue]
    def namespace: String
    def name: String
    def default: blueeyes.json.JsonAST.JValue
  }
  
  sealed trait XField extends Product with blueeyes.json.xschema.XSchema {
    def properties: Map[String, blueeyes.json.JsonAST.JValue]
    def name: String
    def fieldType: blueeyes.json.xschema.XReference
  }
  
  sealed trait XOrder extends Product {
    
  }
  
  case class XRoot(definitions: List[blueeyes.json.xschema.XDefinition], constants: List[blueeyes.json.xschema.XConstant], properties: Map[String, blueeyes.json.JsonAST.JValue]) extends Ordered[blueeyes.json.xschema.XRoot] {
    def compare(that: blueeyes.json.xschema.XRoot): Int = blueeyes.json.xschema.Orderings.XRootOrdering.compare(this, that)
    
  }
  
  case class XDefinitionRef(name: String, namespace: String) extends Ordered[blueeyes.json.xschema.XDefinitionRef] with blueeyes.json.xschema.XReference {
    def compare(that: blueeyes.json.xschema.XDefinitionRef): Int = blueeyes.json.xschema.Orderings.XDefinitionRefOrdering.compare(this, that)
    
  }
  
  case object XBoolean extends blueeyes.json.xschema.XPrimitiveRef
  
  case object XInt extends blueeyes.json.xschema.XPrimitiveRef
  
  case object XLong extends blueeyes.json.xschema.XPrimitiveRef
  
  case object XFloat extends blueeyes.json.xschema.XPrimitiveRef
  
  case object XDouble extends blueeyes.json.xschema.XPrimitiveRef
  
  case object XString extends blueeyes.json.xschema.XPrimitiveRef
  
  case object XJSON extends blueeyes.json.xschema.XPrimitiveRef
  
  case object XDate extends blueeyes.json.xschema.XPrimitiveRef
  
  case class XList(elementType: blueeyes.json.xschema.XReference) extends Ordered[blueeyes.json.xschema.XList] with blueeyes.json.xschema.XCollection {
    def compare(that: blueeyes.json.xschema.XList): Int = blueeyes.json.xschema.Orderings.XListOrdering.compare(this, that)
    
  }
  
  case class XSet(elementType: blueeyes.json.xschema.XReference) extends Ordered[blueeyes.json.xschema.XSet] with blueeyes.json.xschema.XCollection {
    def compare(that: blueeyes.json.xschema.XSet): Int = blueeyes.json.xschema.Orderings.XSetOrdering.compare(this, that)
    
  }
  
  case class XArray(elementType: blueeyes.json.xschema.XReference) extends Ordered[blueeyes.json.xschema.XArray] with blueeyes.json.xschema.XCollection {
    def compare(that: blueeyes.json.xschema.XArray): Int = blueeyes.json.xschema.Orderings.XArrayOrdering.compare(this, that)
    
  }
  
  case class XMap(keyType: blueeyes.json.xschema.XReference, valueType: blueeyes.json.xschema.XReference) extends Ordered[blueeyes.json.xschema.XMap] with blueeyes.json.xschema.XContainerRef {
    def compare(that: blueeyes.json.xschema.XMap): Int = blueeyes.json.xschema.Orderings.XMapOrdering.compare(this, that)
    
  }
  
  case class XOptional(optionalType: blueeyes.json.xschema.XReference) extends Ordered[blueeyes.json.xschema.XOptional] with blueeyes.json.xschema.XContainerRef {
    def compare(that: blueeyes.json.xschema.XOptional): Int = blueeyes.json.xschema.Orderings.XOptionalOrdering.compare(this, that)
    
  }
  
  case class XTuple(types: List[blueeyes.json.xschema.XReference]) extends Ordered[blueeyes.json.xschema.XTuple] with blueeyes.json.xschema.XContainerRef {
    def compare(that: blueeyes.json.xschema.XTuple): Int = blueeyes.json.xschema.Orderings.XTupleOrdering.compare(this, that)
    
  }
  
  /** A product is analogous to a record: it contains fields, which may be any
   * type, have default values, and have a user-defined ordering. Products are
   * the fundamental building blocks used to construct most data structures.
   */
  case class XProduct(name: String, namespace: String, properties: Map[String, blueeyes.json.JsonAST.JValue], terms: List[blueeyes.json.xschema.XField]) extends Ordered[blueeyes.json.xschema.XProduct] with blueeyes.json.xschema.XDefinition with blueeyes.json.xschema.XProductBehavior {
    def compare(that: blueeyes.json.xschema.XProduct): Int = blueeyes.json.xschema.Orderings.XProductOrdering.compare(this, that)
    def referenceTo: blueeyes.json.xschema.XDefinitionRef = blueeyes.json.xschema.XDefinitionRef(name, namespace)
  }
  
  /** A coproduct is a data structure that can assume one of N other types.
   * These types must be either products, or other coproducts -- primitives are
   * not allowed because they cannot be mapped cleanly to most languages (see
   * unions for a disjoint structure that allows primitives). <p> Note that most
   * languages cannot handle coproducts of unions.
   */
  case class XCoproduct(name: String, namespace: String, properties: Map[String, blueeyes.json.JsonAST.JValue], terms: List[blueeyes.json.xschema.XDefinitionRef], default: blueeyes.json.JsonAST.JValue) extends Ordered[blueeyes.json.xschema.XCoproduct] with blueeyes.json.xschema.XMultitype {
    def compare(that: blueeyes.json.xschema.XCoproduct): Int = blueeyes.json.xschema.Orderings.XCoproductOrdering.compare(this, that)
    def referenceTo: blueeyes.json.xschema.XDefinitionRef = blueeyes.json.xschema.XDefinitionRef(name, namespace)
  }
  
  /** A union is a C-style union of N types -- referred to as terms. Unlike
   * coproducts, unions have no effect on the type hierarchy of the specified
   * terms, and the terms may include primitive types, in addition to references
   * to products, coproducts, and other unions. Although unions have names and
   * namespaces, most languages do not have explicit support for union types,
   * and in such cases, no entity will be generated for them; they will be
   * translated into the supertype of all the terms. <p>Some code generators may
   * not be able to handle unions or coproducts that contain unions.
   */
  case class XUnion(name: String, namespace: String, properties: Map[String, blueeyes.json.JsonAST.JValue], terms: List[blueeyes.json.xschema.XReference], default: blueeyes.json.JsonAST.JValue) extends Ordered[blueeyes.json.xschema.XUnion] with blueeyes.json.xschema.XMultitype {
    def compare(that: blueeyes.json.xschema.XUnion): Int = blueeyes.json.xschema.Orderings.XUnionOrdering.compare(this, that)
    def referenceTo: blueeyes.json.xschema.XDefinitionRef = blueeyes.json.xschema.XDefinitionRef(name, namespace)
  }
  
  case class XConstant(name: String, namespace: String, properties: Map[String, blueeyes.json.JsonAST.JValue], constantType: blueeyes.json.xschema.XReference, default: blueeyes.json.JsonAST.JValue) extends Ordered[blueeyes.json.xschema.XConstant] with blueeyes.json.xschema.XSchema {
    def compare(that: blueeyes.json.xschema.XConstant): Int = blueeyes.json.xschema.Orderings.XConstantOrdering.compare(this, that)
    def referenceTo: blueeyes.json.xschema.XDefinitionRef = blueeyes.json.xschema.XDefinitionRef(name, namespace)
  }
  
  case class XRealField(name: String, properties: Map[String, blueeyes.json.JsonAST.JValue], fieldType: blueeyes.json.xschema.XReference, default: blueeyes.json.JsonAST.JValue, order: blueeyes.json.xschema.XOrder) extends Ordered[blueeyes.json.xschema.XRealField] with blueeyes.json.xschema.XField {
    def compare(that: blueeyes.json.xschema.XRealField): Int = blueeyes.json.xschema.Orderings.XRealFieldOrdering.compare(this, that)
    
  }
  
  case class XViewField(name: String, properties: Map[String, blueeyes.json.JsonAST.JValue], fieldType: blueeyes.json.xschema.XReference) extends Ordered[blueeyes.json.xschema.XViewField] with blueeyes.json.xschema.XField {
    def compare(that: blueeyes.json.xschema.XViewField): Int = blueeyes.json.xschema.Orderings.XViewFieldOrdering.compare(this, that)
    
  }
  
  case class XConstantField(name: String, properties: Map[String, blueeyes.json.JsonAST.JValue], fieldType: blueeyes.json.xschema.XReference, default: blueeyes.json.JsonAST.JValue) extends Ordered[blueeyes.json.xschema.XConstantField] with blueeyes.json.xschema.XField {
    def compare(that: blueeyes.json.xschema.XConstantField): Int = blueeyes.json.xschema.Orderings.XConstantFieldOrdering.compare(this, that)
    
  }
  
  case object XOrderAscending extends blueeyes.json.xschema.XOrder
  
  case object XOrderDescending extends blueeyes.json.xschema.XOrder
  
  case object XOrderIgnore extends blueeyes.json.xschema.XOrder
  
  trait Extractors {
    protected def extractField[T](jvalue: JValue, name: String, default: JValue, e: Extractor[T]): T = {
      try {
        e.extract((jvalue \ name -->? classOf[JField]).map(_.value).getOrElse(default))
      }
      catch {
        case _ => e.extract(default)
      }
    }
    
    implicit val XRootExtractor: Extractor[blueeyes.json.xschema.XRoot] = new Extractor[blueeyes.json.xschema.XRoot] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XRoot = {
        XRoot(
          extractField[List[blueeyes.json.xschema.XDefinition]](jvalue, "definitions", JArray(Nil), blueeyes.json.xschema.DefaultExtractors.ListExtractor(blueeyes.json.xschema.Extractors.XDefinitionExtractor)),
          extractField[List[blueeyes.json.xschema.XConstant]](jvalue, "constants", JArray(Nil), blueeyes.json.xschema.DefaultExtractors.ListExtractor(blueeyes.json.xschema.Extractors.XConstantExtractor)),
          extractField[Map[String, blueeyes.json.JsonAST.JValue]](jvalue, "properties", JArray(Nil), blueeyes.json.xschema.DefaultExtractors.StringMapExtractor(blueeyes.json.xschema.DefaultExtractors.JValueExtractor))
        )
      }
    }
    
    lazy val XSchemaExtractorFunction: PartialFunction[JField, blueeyes.json.xschema.XSchema] = ({
      case JField("XDefinition", value) => blueeyes.json.xschema.Extractors.XDefinitionExtractor.extract(value)
      case JField("XReference", value) => blueeyes.json.xschema.Extractors.XReferenceExtractor.extract(value)
      case JField("XField", value) => blueeyes.json.xschema.Extractors.XFieldExtractor.extract(value)
      case JField("XConstant", value) => blueeyes.json.xschema.Extractors.XConstantExtractor.extract(value)
    }: PartialFunction[JField, blueeyes.json.xschema.XSchema]).orElse(blueeyes.json.xschema.Extractors.XDefinitionExtractorFunction).orElse(blueeyes.json.xschema.Extractors.XReferenceExtractorFunction).orElse(blueeyes.json.xschema.Extractors.XFieldExtractorFunction)
    implicit val XSchemaExtractor: Extractor[blueeyes.json.xschema.XSchema] = new Extractor[blueeyes.json.xschema.XSchema] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XSchema = {
        def extract0(jvalue: JValue): Option[blueeyes.json.xschema.XSchema] = {
          (jvalue --> classOf[JObject]).fields.filter(XSchemaExtractorFunction.isDefinedAt _) match {
            case field :: fields => Some(XSchemaExtractorFunction(field))
            case Nil => None
          }
        }
        
        extract0(jvalue) match {
          case Some(v) => v
          case None => extract0(JObject(JField("XString",JObject(Nil))::Nil)) match {
            case Some(v) => v
            case None => error("Expected to find blueeyes.json.xschema.XSchema, but found " + jvalue + ", and default value was invalid")
          }
        }
      }
    }
    
    lazy val XReferenceExtractorFunction: PartialFunction[JField, blueeyes.json.xschema.XReference] = ({
      case JField("XPrimitiveRef", value) => blueeyes.json.xschema.Extractors.XPrimitiveRefExtractor.extract(value)
      case JField("XContainerRef", value) => blueeyes.json.xschema.Extractors.XContainerRefExtractor.extract(value)
      case JField("XDefinitionRef", value) => blueeyes.json.xschema.Extractors.XDefinitionRefExtractor.extract(value)
    }: PartialFunction[JField, blueeyes.json.xschema.XReference]).orElse(blueeyes.json.xschema.Extractors.XPrimitiveRefExtractorFunction).orElse(blueeyes.json.xschema.Extractors.XContainerRefExtractorFunction)
    implicit val XReferenceExtractor: Extractor[blueeyes.json.xschema.XReference] = new Extractor[blueeyes.json.xschema.XReference] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XReference = {
        def extract0(jvalue: JValue): Option[blueeyes.json.xschema.XReference] = {
          (jvalue --> classOf[JObject]).fields.filter(XReferenceExtractorFunction.isDefinedAt _) match {
            case field :: fields => Some(XReferenceExtractorFunction(field))
            case Nil => None
          }
        }
        
        extract0(jvalue) match {
          case Some(v) => v
          case None => extract0(JObject(JField("XString",JObject(Nil))::Nil)) match {
            case Some(v) => v
            case None => error("Expected to find blueeyes.json.xschema.XReference, but found " + jvalue + ", and default value was invalid")
          }
        }
      }
    }
    
    lazy val XPrimitiveRefExtractorFunction: PartialFunction[JField, blueeyes.json.xschema.XPrimitiveRef] = ({
      case JField("XBoolean", value) => blueeyes.json.xschema.Extractors.XBooleanExtractor.extract(value)
      case JField("XInt", value) => blueeyes.json.xschema.Extractors.XIntExtractor.extract(value)
      case JField("XLong", value) => blueeyes.json.xschema.Extractors.XLongExtractor.extract(value)
      case JField("XFloat", value) => blueeyes.json.xschema.Extractors.XFloatExtractor.extract(value)
      case JField("XDouble", value) => blueeyes.json.xschema.Extractors.XDoubleExtractor.extract(value)
      case JField("XString", value) => blueeyes.json.xschema.Extractors.XStringExtractor.extract(value)
      case JField("XJSON", value) => blueeyes.json.xschema.Extractors.XJSONExtractor.extract(value)
      case JField("XDate", value) => blueeyes.json.xschema.Extractors.XDateExtractor.extract(value)
    }: PartialFunction[JField, blueeyes.json.xschema.XPrimitiveRef])
    implicit val XPrimitiveRefExtractor: Extractor[blueeyes.json.xschema.XPrimitiveRef] = new Extractor[blueeyes.json.xschema.XPrimitiveRef] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XPrimitiveRef = {
        def extract0(jvalue: JValue): Option[blueeyes.json.xschema.XPrimitiveRef] = {
          (jvalue --> classOf[JObject]).fields.filter(XPrimitiveRefExtractorFunction.isDefinedAt _) match {
            case field :: fields => Some(XPrimitiveRefExtractorFunction(field))
            case Nil => None
          }
        }
        
        extract0(jvalue) match {
          case Some(v) => v
          case None => extract0(JObject(JField("XString",JObject(Nil))::Nil)) match {
            case Some(v) => v
            case None => error("Expected to find blueeyes.json.xschema.XPrimitiveRef, but found " + jvalue + ", and default value was invalid")
          }
        }
      }
    }
    
    lazy val XContainerRefExtractorFunction: PartialFunction[JField, blueeyes.json.xschema.XContainerRef] = ({
      case JField("XCollection", value) => blueeyes.json.xschema.Extractors.XCollectionExtractor.extract(value)
      case JField("XMap", value) => blueeyes.json.xschema.Extractors.XMapExtractor.extract(value)
      case JField("XOptional", value) => blueeyes.json.xschema.Extractors.XOptionalExtractor.extract(value)
      case JField("XTuple", value) => blueeyes.json.xschema.Extractors.XTupleExtractor.extract(value)
    }: PartialFunction[JField, blueeyes.json.xschema.XContainerRef]).orElse(blueeyes.json.xschema.Extractors.XCollectionExtractorFunction)
    implicit val XContainerRefExtractor: Extractor[blueeyes.json.xschema.XContainerRef] = new Extractor[blueeyes.json.xschema.XContainerRef] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XContainerRef = {
        def extract0(jvalue: JValue): Option[blueeyes.json.xschema.XContainerRef] = {
          (jvalue --> classOf[JObject]).fields.filter(XContainerRefExtractorFunction.isDefinedAt _) match {
            case field :: fields => Some(XContainerRefExtractorFunction(field))
            case Nil => None
          }
        }
        
        extract0(jvalue) match {
          case Some(v) => v
          case None => extract0(JObject(JField("XList",JObject(JField("elementType",JObject(JField("XString",JObject(Nil))::Nil))::Nil))::Nil)) match {
            case Some(v) => v
            case None => error("Expected to find blueeyes.json.xschema.XContainerRef, but found " + jvalue + ", and default value was invalid")
          }
        }
      }
    }
    
    implicit val XDefinitionRefExtractor: Extractor[blueeyes.json.xschema.XDefinitionRef] = new Extractor[blueeyes.json.xschema.XDefinitionRef] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XDefinitionRef = {
        XDefinitionRef(
          extractField[String](jvalue, "name", JString(""), blueeyes.json.xschema.DefaultExtractors.StringExtractor),
          extractField[String](jvalue, "namespace", JString(""), blueeyes.json.xschema.DefaultExtractors.StringExtractor)
        )
      }
    }
    
    implicit val XBooleanExtractor: Extractor[blueeyes.json.xschema.XBoolean.type] = new Extractor[blueeyes.json.xschema.XBoolean.type] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XBoolean.type = {
        XBoolean
      }
    }
    
    implicit val XIntExtractor: Extractor[blueeyes.json.xschema.XInt.type] = new Extractor[blueeyes.json.xschema.XInt.type] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XInt.type = {
        XInt
      }
    }
    
    implicit val XLongExtractor: Extractor[blueeyes.json.xschema.XLong.type] = new Extractor[blueeyes.json.xschema.XLong.type] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XLong.type = {
        XLong
      }
    }
    
    implicit val XFloatExtractor: Extractor[blueeyes.json.xschema.XFloat.type] = new Extractor[blueeyes.json.xschema.XFloat.type] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XFloat.type = {
        XFloat
      }
    }
    
    implicit val XDoubleExtractor: Extractor[blueeyes.json.xschema.XDouble.type] = new Extractor[blueeyes.json.xschema.XDouble.type] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XDouble.type = {
        XDouble
      }
    }
    
    implicit val XStringExtractor: Extractor[blueeyes.json.xschema.XString.type] = new Extractor[blueeyes.json.xschema.XString.type] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XString.type = {
        XString
      }
    }
    
    implicit val XJSONExtractor: Extractor[blueeyes.json.xschema.XJSON.type] = new Extractor[blueeyes.json.xschema.XJSON.type] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XJSON.type = {
        XJSON
      }
    }
    
    implicit val XDateExtractor: Extractor[blueeyes.json.xschema.XDate.type] = new Extractor[blueeyes.json.xschema.XDate.type] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XDate.type = {
        XDate
      }
    }
    
    lazy val XCollectionExtractorFunction: PartialFunction[JField, blueeyes.json.xschema.XCollection] = ({
      case JField("XList", value) => blueeyes.json.xschema.Extractors.XListExtractor.extract(value)
      case JField("XSet", value) => blueeyes.json.xschema.Extractors.XSetExtractor.extract(value)
      case JField("XArray", value) => blueeyes.json.xschema.Extractors.XArrayExtractor.extract(value)
    }: PartialFunction[JField, blueeyes.json.xschema.XCollection])
    implicit val XCollectionExtractor: Extractor[blueeyes.json.xschema.XCollection] = new Extractor[blueeyes.json.xschema.XCollection] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XCollection = {
        def extract0(jvalue: JValue): Option[blueeyes.json.xschema.XCollection] = {
          (jvalue --> classOf[JObject]).fields.filter(XCollectionExtractorFunction.isDefinedAt _) match {
            case field :: fields => Some(XCollectionExtractorFunction(field))
            case Nil => None
          }
        }
        
        extract0(jvalue) match {
          case Some(v) => v
          case None => extract0(JObject(JField("XList",JObject(JField("elementType",JObject(JField("XString",JObject(Nil))::Nil))::Nil))::Nil)) match {
            case Some(v) => v
            case None => error("Expected to find blueeyes.json.xschema.XCollection, but found " + jvalue + ", and default value was invalid")
          }
        }
      }
    }
    
    implicit val XListExtractor: Extractor[blueeyes.json.xschema.XList] = new Extractor[blueeyes.json.xschema.XList] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XList = {
        XList(
          extractField[blueeyes.json.xschema.XReference](jvalue, "elementType", JObject(JField("XDefinitionRef",JObject(JField("name",JString(""))::JField("namespace",JString(""))::Nil))::Nil), blueeyes.json.xschema.Extractors.XReferenceExtractor)
        )
      }
    }
    
    implicit val XSetExtractor: Extractor[blueeyes.json.xschema.XSet] = new Extractor[blueeyes.json.xschema.XSet] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XSet = {
        XSet(
          extractField[blueeyes.json.xschema.XReference](jvalue, "elementType", JObject(JField("XDefinitionRef",JObject(JField("name",JString(""))::JField("namespace",JString(""))::Nil))::Nil), blueeyes.json.xschema.Extractors.XReferenceExtractor)
        )
      }
    }
    
    implicit val XArrayExtractor: Extractor[blueeyes.json.xschema.XArray] = new Extractor[blueeyes.json.xschema.XArray] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XArray = {
        XArray(
          extractField[blueeyes.json.xschema.XReference](jvalue, "elementType", JObject(JField("XDefinitionRef",JObject(JField("name",JString(""))::JField("namespace",JString(""))::Nil))::Nil), blueeyes.json.xschema.Extractors.XReferenceExtractor)
        )
      }
    }
    
    implicit val XMapExtractor: Extractor[blueeyes.json.xschema.XMap] = new Extractor[blueeyes.json.xschema.XMap] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XMap = {
        XMap(
          extractField[blueeyes.json.xschema.XReference](jvalue, "keyType", JObject(JField("XDefinitionRef",JObject(JField("name",JString(""))::JField("namespace",JString(""))::Nil))::Nil), blueeyes.json.xschema.Extractors.XReferenceExtractor),
          extractField[blueeyes.json.xschema.XReference](jvalue, "valueType", JObject(JField("XDefinitionRef",JObject(JField("name",JString(""))::JField("namespace",JString(""))::Nil))::Nil), blueeyes.json.xschema.Extractors.XReferenceExtractor)
        )
      }
    }
    
    implicit val XOptionalExtractor: Extractor[blueeyes.json.xschema.XOptional] = new Extractor[blueeyes.json.xschema.XOptional] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XOptional = {
        XOptional(
          extractField[blueeyes.json.xschema.XReference](jvalue, "optionalType", JObject(JField("XDefinitionRef",JObject(JField("name",JString(""))::JField("namespace",JString(""))::Nil))::Nil), blueeyes.json.xschema.Extractors.XReferenceExtractor)
        )
      }
    }
    
    implicit val XTupleExtractor: Extractor[blueeyes.json.xschema.XTuple] = new Extractor[blueeyes.json.xschema.XTuple] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XTuple = {
        XTuple(
          extractField[List[blueeyes.json.xschema.XReference]](jvalue, "types", JArray(Nil), blueeyes.json.xschema.DefaultExtractors.ListExtractor(blueeyes.json.xschema.Extractors.XReferenceExtractor))
        )
      }
    }
    
    lazy val XDefinitionExtractorFunction: PartialFunction[JField, blueeyes.json.xschema.XDefinition] = ({
      case JField("XProduct", value) => blueeyes.json.xschema.Extractors.XProductExtractor.extract(value)
      case JField("XMultitype", value) => blueeyes.json.xschema.Extractors.XMultitypeExtractor.extract(value)
    }: PartialFunction[JField, blueeyes.json.xschema.XDefinition]).orElse(blueeyes.json.xschema.Extractors.XMultitypeExtractorFunction)
    implicit val XDefinitionExtractor: Extractor[blueeyes.json.xschema.XDefinition] = new Extractor[blueeyes.json.xschema.XDefinition] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XDefinition = {
        def extract0(jvalue: JValue): Option[blueeyes.json.xschema.XDefinition] = {
          (jvalue --> classOf[JObject]).fields.filter(XDefinitionExtractorFunction.isDefinedAt _) match {
            case field :: fields => Some(XDefinitionExtractorFunction(field))
            case Nil => None
          }
        }
        
        extract0(jvalue) match {
          case Some(v) => v
          case None => extract0(JObject(JField("XProduct",JObject(Nil))::Nil)) match {
            case Some(v) => v
            case None => error("Expected to find blueeyes.json.xschema.XDefinition, but found " + jvalue + ", and default value was invalid")
          }
        }
      }
    }
    
    lazy val XMultitypeExtractorFunction: PartialFunction[JField, blueeyes.json.xschema.XMultitype] = ({
      case JField("XCoproduct", value) => blueeyes.json.xschema.Extractors.XCoproductExtractor.extract(value)
      case JField("XUnion", value) => blueeyes.json.xschema.Extractors.XUnionExtractor.extract(value)
    }: PartialFunction[JField, blueeyes.json.xschema.XMultitype])
    implicit val XMultitypeExtractor: Extractor[blueeyes.json.xschema.XMultitype] = new Extractor[blueeyes.json.xschema.XMultitype] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XMultitype = {
        def extract0(jvalue: JValue): Option[blueeyes.json.xschema.XMultitype] = {
          (jvalue --> classOf[JObject]).fields.filter(XMultitypeExtractorFunction.isDefinedAt _) match {
            case field :: fields => Some(XMultitypeExtractorFunction(field))
            case Nil => None
          }
        }
        
        extract0(jvalue) match {
          case Some(v) => v
          case None => extract0(JObject(JField("XCoproduct",JObject(Nil))::Nil)) match {
            case Some(v) => v
            case None => error("Expected to find blueeyes.json.xschema.XMultitype, but found " + jvalue + ", and default value was invalid")
          }
        }
      }
    }
    
    lazy val XFieldExtractorFunction: PartialFunction[JField, blueeyes.json.xschema.XField] = ({
      case JField("XRealField", value) => blueeyes.json.xschema.Extractors.XRealFieldExtractor.extract(value)
      case JField("XViewField", value) => blueeyes.json.xschema.Extractors.XViewFieldExtractor.extract(value)
      case JField("XConstantField", value) => blueeyes.json.xschema.Extractors.XConstantFieldExtractor.extract(value)
    }: PartialFunction[JField, blueeyes.json.xschema.XField])
    implicit val XFieldExtractor: Extractor[blueeyes.json.xschema.XField] = new Extractor[blueeyes.json.xschema.XField] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XField = {
        def extract0(jvalue: JValue): Option[blueeyes.json.xschema.XField] = {
          (jvalue --> classOf[JObject]).fields.filter(XFieldExtractorFunction.isDefinedAt _) match {
            case field :: fields => Some(XFieldExtractorFunction(field))
            case Nil => None
          }
        }
        
        extract0(jvalue) match {
          case Some(v) => v
          case None => extract0(JObject(JField("XRealField",JObject(Nil))::Nil)) match {
            case Some(v) => v
            case None => error("Expected to find blueeyes.json.xschema.XField, but found " + jvalue + ", and default value was invalid")
          }
        }
      }
    }
    
    implicit val XProductExtractor: Extractor[blueeyes.json.xschema.XProduct] = new Extractor[blueeyes.json.xschema.XProduct] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XProduct = {
        XProduct(
          extractField[String](jvalue, "name", JString(""), blueeyes.json.xschema.DefaultExtractors.StringExtractor),
          extractField[String](jvalue, "namespace", JString(""), blueeyes.json.xschema.DefaultExtractors.StringExtractor),
          extractField[Map[String, blueeyes.json.JsonAST.JValue]](jvalue, "properties", JArray(Nil), blueeyes.json.xschema.DefaultExtractors.StringMapExtractor(blueeyes.json.xschema.DefaultExtractors.JValueExtractor)),
          extractField[List[blueeyes.json.xschema.XField]](jvalue, "terms", JArray(Nil), blueeyes.json.xschema.DefaultExtractors.ListExtractor(blueeyes.json.xschema.Extractors.XFieldExtractor))
        )
      }
    }
    
    implicit val XCoproductExtractor: Extractor[blueeyes.json.xschema.XCoproduct] = new Extractor[blueeyes.json.xschema.XCoproduct] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XCoproduct = {
        XCoproduct(
          extractField[String](jvalue, "name", JString(""), blueeyes.json.xschema.DefaultExtractors.StringExtractor),
          extractField[String](jvalue, "namespace", JString(""), blueeyes.json.xschema.DefaultExtractors.StringExtractor),
          extractField[Map[String, blueeyes.json.JsonAST.JValue]](jvalue, "properties", JArray(Nil), blueeyes.json.xschema.DefaultExtractors.StringMapExtractor(blueeyes.json.xschema.DefaultExtractors.JValueExtractor)),
          extractField[List[blueeyes.json.xschema.XDefinitionRef]](jvalue, "terms", JArray(Nil), blueeyes.json.xschema.DefaultExtractors.ListExtractor(blueeyes.json.xschema.Extractors.XDefinitionRefExtractor)),
          extractField[blueeyes.json.JsonAST.JValue](jvalue, "default", JString(""), blueeyes.json.xschema.DefaultExtractors.JValueExtractor)
        )
      }
    }
    
    implicit val XUnionExtractor: Extractor[blueeyes.json.xschema.XUnion] = new Extractor[blueeyes.json.xschema.XUnion] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XUnion = {
        XUnion(
          extractField[String](jvalue, "name", JString(""), blueeyes.json.xschema.DefaultExtractors.StringExtractor),
          extractField[String](jvalue, "namespace", JString(""), blueeyes.json.xschema.DefaultExtractors.StringExtractor),
          extractField[Map[String, blueeyes.json.JsonAST.JValue]](jvalue, "properties", JArray(Nil), blueeyes.json.xschema.DefaultExtractors.StringMapExtractor(blueeyes.json.xschema.DefaultExtractors.JValueExtractor)),
          extractField[List[blueeyes.json.xschema.XReference]](jvalue, "terms", JArray(Nil), blueeyes.json.xschema.DefaultExtractors.ListExtractor(blueeyes.json.xschema.Extractors.XReferenceExtractor)),
          extractField[blueeyes.json.JsonAST.JValue](jvalue, "default", JString(""), blueeyes.json.xschema.DefaultExtractors.JValueExtractor)
        )
      }
    }
    
    implicit val XConstantExtractor: Extractor[blueeyes.json.xschema.XConstant] = new Extractor[blueeyes.json.xschema.XConstant] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XConstant = {
        XConstant(
          extractField[String](jvalue, "name", JString(""), blueeyes.json.xschema.DefaultExtractors.StringExtractor),
          extractField[String](jvalue, "namespace", JString(""), blueeyes.json.xschema.DefaultExtractors.StringExtractor),
          extractField[Map[String, blueeyes.json.JsonAST.JValue]](jvalue, "properties", JArray(Nil), blueeyes.json.xschema.DefaultExtractors.StringMapExtractor(blueeyes.json.xschema.DefaultExtractors.JValueExtractor)),
          extractField[blueeyes.json.xschema.XReference](jvalue, "constantType", JObject(JField("XString",JObject(Nil))::Nil), blueeyes.json.xschema.Extractors.XReferenceExtractor),
          extractField[blueeyes.json.JsonAST.JValue](jvalue, "default", JString(""), blueeyes.json.xschema.DefaultExtractors.JValueExtractor)
        )
      }
    }
    
    implicit val XRealFieldExtractor: Extractor[blueeyes.json.xschema.XRealField] = new Extractor[blueeyes.json.xschema.XRealField] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XRealField = {
        XRealField(
          extractField[String](jvalue, "name", JString(""), blueeyes.json.xschema.DefaultExtractors.StringExtractor),
          extractField[Map[String, blueeyes.json.JsonAST.JValue]](jvalue, "properties", JArray(Nil), blueeyes.json.xschema.DefaultExtractors.StringMapExtractor(blueeyes.json.xschema.DefaultExtractors.JValueExtractor)),
          extractField[blueeyes.json.xschema.XReference](jvalue, "fieldType", JObject(JField("XString",JObject(Nil))::Nil), blueeyes.json.xschema.Extractors.XReferenceExtractor),
          extractField[blueeyes.json.JsonAST.JValue](jvalue, "default", JString(""), blueeyes.json.xschema.DefaultExtractors.JValueExtractor),
          extractField[blueeyes.json.xschema.XOrder](jvalue, "order", JObject(JField("XOrderAscending",JObject(Nil))::Nil), blueeyes.json.xschema.Extractors.XOrderExtractor)
        )
      }
    }
    
    implicit val XViewFieldExtractor: Extractor[blueeyes.json.xschema.XViewField] = new Extractor[blueeyes.json.xschema.XViewField] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XViewField = {
        XViewField(
          extractField[String](jvalue, "name", JString(""), blueeyes.json.xschema.DefaultExtractors.StringExtractor),
          extractField[Map[String, blueeyes.json.JsonAST.JValue]](jvalue, "properties", JArray(Nil), blueeyes.json.xschema.DefaultExtractors.StringMapExtractor(blueeyes.json.xschema.DefaultExtractors.JValueExtractor)),
          extractField[blueeyes.json.xschema.XReference](jvalue, "fieldType", JObject(JField("XDefinitionRef",JObject(JField("name",JString(""))::JField("namespace",JString(""))::Nil))::Nil), blueeyes.json.xschema.Extractors.XReferenceExtractor)
        )
      }
    }
    
    implicit val XConstantFieldExtractor: Extractor[blueeyes.json.xschema.XConstantField] = new Extractor[blueeyes.json.xschema.XConstantField] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XConstantField = {
        XConstantField(
          extractField[String](jvalue, "name", JString(""), blueeyes.json.xschema.DefaultExtractors.StringExtractor),
          extractField[Map[String, blueeyes.json.JsonAST.JValue]](jvalue, "properties", JArray(Nil), blueeyes.json.xschema.DefaultExtractors.StringMapExtractor(blueeyes.json.xschema.DefaultExtractors.JValueExtractor)),
          extractField[blueeyes.json.xschema.XReference](jvalue, "fieldType", JObject(JField("XString",JObject(Nil))::Nil), blueeyes.json.xschema.Extractors.XReferenceExtractor),
          extractField[blueeyes.json.JsonAST.JValue](jvalue, "default", JString(""), blueeyes.json.xschema.DefaultExtractors.JValueExtractor)
        )
      }
    }
    
    lazy val XOrderExtractorFunction: PartialFunction[JField, blueeyes.json.xschema.XOrder] = ({
      case JField("XOrderAscending", value) => blueeyes.json.xschema.Extractors.XOrderAscendingExtractor.extract(value)
      case JField("XOrderDescending", value) => blueeyes.json.xschema.Extractors.XOrderDescendingExtractor.extract(value)
      case JField("XOrderIgnore", value) => blueeyes.json.xschema.Extractors.XOrderIgnoreExtractor.extract(value)
    }: PartialFunction[JField, blueeyes.json.xschema.XOrder])
    implicit val XOrderExtractor: Extractor[blueeyes.json.xschema.XOrder] = new Extractor[blueeyes.json.xschema.XOrder] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XOrder = {
        def extract0(jvalue: JValue): Option[blueeyes.json.xschema.XOrder] = {
          (jvalue --> classOf[JObject]).fields.filter(XOrderExtractorFunction.isDefinedAt _) match {
            case field :: fields => Some(XOrderExtractorFunction(field))
            case Nil => None
          }
        }
        
        extract0(jvalue) match {
          case Some(v) => v
          case None => extract0(JObject(JField("XOrderAscending",JObject(Nil))::Nil)) match {
            case Some(v) => v
            case None => error("Expected to find blueeyes.json.xschema.XOrder, but found " + jvalue + ", and default value was invalid")
          }
        }
      }
    }
    
    implicit val XOrderAscendingExtractor: Extractor[blueeyes.json.xschema.XOrderAscending.type] = new Extractor[blueeyes.json.xschema.XOrderAscending.type] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XOrderAscending.type = {
        XOrderAscending
      }
    }
    
    implicit val XOrderDescendingExtractor: Extractor[blueeyes.json.xschema.XOrderDescending.type] = new Extractor[blueeyes.json.xschema.XOrderDescending.type] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XOrderDescending.type = {
        XOrderDescending
      }
    }
    
    implicit val XOrderIgnoreExtractor: Extractor[blueeyes.json.xschema.XOrderIgnore.type] = new Extractor[blueeyes.json.xschema.XOrderIgnore.type] {
      def extract(jvalue: JValue): blueeyes.json.xschema.XOrderIgnore.type = {
        XOrderIgnore
      }
    }
  }
  object Extractors extends Extractors
  
  trait Decomposers {
    implicit val XRootDecomposer: Decomposer[blueeyes.json.xschema.XRoot] = new Decomposer[blueeyes.json.xschema.XRoot] {
      def decompose(tvalue: blueeyes.json.xschema.XRoot): JValue = {
        JObject(
          JField("definitions", blueeyes.json.xschema.DefaultDecomposers.ListDecomposer(blueeyes.json.xschema.Decomposers.XDefinitionDecomposer).decompose(tvalue.definitions)) ::
          JField("constants", blueeyes.json.xschema.DefaultDecomposers.ListDecomposer(blueeyes.json.xschema.Decomposers.XConstantDecomposer).decompose(tvalue.constants)) ::
          JField("properties", blueeyes.json.xschema.DefaultDecomposers.StringMapDecomposer(blueeyes.json.xschema.DefaultDecomposers.JValueDecomposer).decompose(tvalue.properties)) :: Nil
        )
      }
    }
    
    implicit val XSchemaDecomposer: Decomposer[blueeyes.json.xschema.XSchema] = new Decomposer[blueeyes.json.xschema.XSchema] {
      def decompose(tvalue: blueeyes.json.xschema.XSchema): JValue = {
        tvalue match {
          case x: blueeyes.json.xschema.XProduct => JObject(JField("XProduct", blueeyes.json.xschema.Decomposers.XProductDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XCoproduct => JObject(JField("XCoproduct", blueeyes.json.xschema.Decomposers.XCoproductDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XUnion => JObject(JField("XUnion", blueeyes.json.xschema.Decomposers.XUnionDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XBoolean.type => JObject(JField("XBoolean", blueeyes.json.xschema.Decomposers.XBooleanDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XInt.type => JObject(JField("XInt", blueeyes.json.xschema.Decomposers.XIntDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XLong.type => JObject(JField("XLong", blueeyes.json.xschema.Decomposers.XLongDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XFloat.type => JObject(JField("XFloat", blueeyes.json.xschema.Decomposers.XFloatDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XDouble.type => JObject(JField("XDouble", blueeyes.json.xschema.Decomposers.XDoubleDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XString.type => JObject(JField("XString", blueeyes.json.xschema.Decomposers.XStringDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XJSON.type => JObject(JField("XJSON", blueeyes.json.xschema.Decomposers.XJSONDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XDate.type => JObject(JField("XDate", blueeyes.json.xschema.Decomposers.XDateDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XList => JObject(JField("XList", blueeyes.json.xschema.Decomposers.XListDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XSet => JObject(JField("XSet", blueeyes.json.xschema.Decomposers.XSetDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XArray => JObject(JField("XArray", blueeyes.json.xschema.Decomposers.XArrayDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XMap => JObject(JField("XMap", blueeyes.json.xschema.Decomposers.XMapDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XOptional => JObject(JField("XOptional", blueeyes.json.xschema.Decomposers.XOptionalDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XTuple => JObject(JField("XTuple", blueeyes.json.xschema.Decomposers.XTupleDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XDefinitionRef => JObject(JField("XDefinitionRef", blueeyes.json.xschema.Decomposers.XDefinitionRefDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XRealField => JObject(JField("XRealField", blueeyes.json.xschema.Decomposers.XRealFieldDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XViewField => JObject(JField("XViewField", blueeyes.json.xschema.Decomposers.XViewFieldDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XConstantField => JObject(JField("XConstantField", blueeyes.json.xschema.Decomposers.XConstantFieldDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XConstant => JObject(JField("XConstant", blueeyes.json.xschema.Decomposers.XConstantDecomposer.decompose(x)) :: Nil)
        }
      }
    }
    
    implicit val XReferenceDecomposer: Decomposer[blueeyes.json.xschema.XReference] = new Decomposer[blueeyes.json.xschema.XReference] {
      def decompose(tvalue: blueeyes.json.xschema.XReference): JValue = {
        tvalue match {
          case x: blueeyes.json.xschema.XBoolean.type => JObject(JField("XBoolean", blueeyes.json.xschema.Decomposers.XBooleanDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XInt.type => JObject(JField("XInt", blueeyes.json.xschema.Decomposers.XIntDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XLong.type => JObject(JField("XLong", blueeyes.json.xschema.Decomposers.XLongDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XFloat.type => JObject(JField("XFloat", blueeyes.json.xschema.Decomposers.XFloatDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XDouble.type => JObject(JField("XDouble", blueeyes.json.xschema.Decomposers.XDoubleDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XString.type => JObject(JField("XString", blueeyes.json.xschema.Decomposers.XStringDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XJSON.type => JObject(JField("XJSON", blueeyes.json.xschema.Decomposers.XJSONDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XDate.type => JObject(JField("XDate", blueeyes.json.xschema.Decomposers.XDateDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XList => JObject(JField("XList", blueeyes.json.xschema.Decomposers.XListDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XSet => JObject(JField("XSet", blueeyes.json.xschema.Decomposers.XSetDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XArray => JObject(JField("XArray", blueeyes.json.xschema.Decomposers.XArrayDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XMap => JObject(JField("XMap", blueeyes.json.xschema.Decomposers.XMapDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XOptional => JObject(JField("XOptional", blueeyes.json.xschema.Decomposers.XOptionalDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XTuple => JObject(JField("XTuple", blueeyes.json.xschema.Decomposers.XTupleDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XDefinitionRef => JObject(JField("XDefinitionRef", blueeyes.json.xschema.Decomposers.XDefinitionRefDecomposer.decompose(x)) :: Nil)
        }
      }
    }
    
    implicit val XPrimitiveRefDecomposer: Decomposer[blueeyes.json.xschema.XPrimitiveRef] = new Decomposer[blueeyes.json.xschema.XPrimitiveRef] {
      def decompose(tvalue: blueeyes.json.xschema.XPrimitiveRef): JValue = {
        tvalue match {
          case x: blueeyes.json.xschema.XBoolean.type => JObject(JField("XBoolean", blueeyes.json.xschema.Decomposers.XBooleanDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XInt.type => JObject(JField("XInt", blueeyes.json.xschema.Decomposers.XIntDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XLong.type => JObject(JField("XLong", blueeyes.json.xschema.Decomposers.XLongDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XFloat.type => JObject(JField("XFloat", blueeyes.json.xschema.Decomposers.XFloatDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XDouble.type => JObject(JField("XDouble", blueeyes.json.xschema.Decomposers.XDoubleDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XString.type => JObject(JField("XString", blueeyes.json.xschema.Decomposers.XStringDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XJSON.type => JObject(JField("XJSON", blueeyes.json.xschema.Decomposers.XJSONDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XDate.type => JObject(JField("XDate", blueeyes.json.xschema.Decomposers.XDateDecomposer.decompose(x)) :: Nil)
        }
      }
    }
    
    implicit val XContainerRefDecomposer: Decomposer[blueeyes.json.xschema.XContainerRef] = new Decomposer[blueeyes.json.xschema.XContainerRef] {
      def decompose(tvalue: blueeyes.json.xschema.XContainerRef): JValue = {
        tvalue match {
          case x: blueeyes.json.xschema.XList => JObject(JField("XList", blueeyes.json.xschema.Decomposers.XListDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XSet => JObject(JField("XSet", blueeyes.json.xschema.Decomposers.XSetDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XArray => JObject(JField("XArray", blueeyes.json.xschema.Decomposers.XArrayDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XMap => JObject(JField("XMap", blueeyes.json.xschema.Decomposers.XMapDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XOptional => JObject(JField("XOptional", blueeyes.json.xschema.Decomposers.XOptionalDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XTuple => JObject(JField("XTuple", blueeyes.json.xschema.Decomposers.XTupleDecomposer.decompose(x)) :: Nil)
        }
      }
    }
    
    implicit val XDefinitionRefDecomposer: Decomposer[blueeyes.json.xschema.XDefinitionRef] = new Decomposer[blueeyes.json.xschema.XDefinitionRef] {
      def decompose(tvalue: blueeyes.json.xschema.XDefinitionRef): JValue = {
        JObject(
          JField("name", blueeyes.json.xschema.DefaultDecomposers.StringDecomposer.decompose(tvalue.name)) ::
          JField("namespace", blueeyes.json.xschema.DefaultDecomposers.StringDecomposer.decompose(tvalue.namespace)) :: Nil
        )
      }
    }
    
    implicit val XBooleanDecomposer: Decomposer[blueeyes.json.xschema.XBoolean.type] = new Decomposer[blueeyes.json.xschema.XBoolean.type] {
      def decompose(tvalue: blueeyes.json.xschema.XBoolean.type): JValue = {
        JObject(
           Nil
        )
      }
    }
    
    implicit val XIntDecomposer: Decomposer[blueeyes.json.xschema.XInt.type] = new Decomposer[blueeyes.json.xschema.XInt.type] {
      def decompose(tvalue: blueeyes.json.xschema.XInt.type): JValue = {
        JObject(
           Nil
        )
      }
    }
    
    implicit val XLongDecomposer: Decomposer[blueeyes.json.xschema.XLong.type] = new Decomposer[blueeyes.json.xschema.XLong.type] {
      def decompose(tvalue: blueeyes.json.xschema.XLong.type): JValue = {
        JObject(
           Nil
        )
      }
    }
    
    implicit val XFloatDecomposer: Decomposer[blueeyes.json.xschema.XFloat.type] = new Decomposer[blueeyes.json.xschema.XFloat.type] {
      def decompose(tvalue: blueeyes.json.xschema.XFloat.type): JValue = {
        JObject(
           Nil
        )
      }
    }
    
    implicit val XDoubleDecomposer: Decomposer[blueeyes.json.xschema.XDouble.type] = new Decomposer[blueeyes.json.xschema.XDouble.type] {
      def decompose(tvalue: blueeyes.json.xschema.XDouble.type): JValue = {
        JObject(
           Nil
        )
      }
    }
    
    implicit val XStringDecomposer: Decomposer[blueeyes.json.xschema.XString.type] = new Decomposer[blueeyes.json.xschema.XString.type] {
      def decompose(tvalue: blueeyes.json.xschema.XString.type): JValue = {
        JObject(
           Nil
        )
      }
    }
    
    implicit val XJSONDecomposer: Decomposer[blueeyes.json.xschema.XJSON.type] = new Decomposer[blueeyes.json.xschema.XJSON.type] {
      def decompose(tvalue: blueeyes.json.xschema.XJSON.type): JValue = {
        JObject(
           Nil
        )
      }
    }
    
    implicit val XDateDecomposer: Decomposer[blueeyes.json.xschema.XDate.type] = new Decomposer[blueeyes.json.xschema.XDate.type] {
      def decompose(tvalue: blueeyes.json.xschema.XDate.type): JValue = {
        JObject(
           Nil
        )
      }
    }
    
    implicit val XCollectionDecomposer: Decomposer[blueeyes.json.xschema.XCollection] = new Decomposer[blueeyes.json.xschema.XCollection] {
      def decompose(tvalue: blueeyes.json.xschema.XCollection): JValue = {
        tvalue match {
          case x: blueeyes.json.xschema.XList => JObject(JField("XList", blueeyes.json.xschema.Decomposers.XListDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XSet => JObject(JField("XSet", blueeyes.json.xschema.Decomposers.XSetDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XArray => JObject(JField("XArray", blueeyes.json.xschema.Decomposers.XArrayDecomposer.decompose(x)) :: Nil)
        }
      }
    }
    
    implicit val XListDecomposer: Decomposer[blueeyes.json.xschema.XList] = new Decomposer[blueeyes.json.xschema.XList] {
      def decompose(tvalue: blueeyes.json.xschema.XList): JValue = {
        JObject(
          JField("elementType", blueeyes.json.xschema.Decomposers.XReferenceDecomposer.decompose(tvalue.elementType)) :: Nil
        )
      }
    }
    
    implicit val XSetDecomposer: Decomposer[blueeyes.json.xschema.XSet] = new Decomposer[blueeyes.json.xschema.XSet] {
      def decompose(tvalue: blueeyes.json.xschema.XSet): JValue = {
        JObject(
          JField("elementType", blueeyes.json.xschema.Decomposers.XReferenceDecomposer.decompose(tvalue.elementType)) :: Nil
        )
      }
    }
    
    implicit val XArrayDecomposer: Decomposer[blueeyes.json.xschema.XArray] = new Decomposer[blueeyes.json.xschema.XArray] {
      def decompose(tvalue: blueeyes.json.xschema.XArray): JValue = {
        JObject(
          JField("elementType", blueeyes.json.xschema.Decomposers.XReferenceDecomposer.decompose(tvalue.elementType)) :: Nil
        )
      }
    }
    
    implicit val XMapDecomposer: Decomposer[blueeyes.json.xschema.XMap] = new Decomposer[blueeyes.json.xschema.XMap] {
      def decompose(tvalue: blueeyes.json.xschema.XMap): JValue = {
        JObject(
          JField("keyType", blueeyes.json.xschema.Decomposers.XReferenceDecomposer.decompose(tvalue.keyType)) ::
          JField("valueType", blueeyes.json.xschema.Decomposers.XReferenceDecomposer.decompose(tvalue.valueType)) :: Nil
        )
      }
    }
    
    implicit val XOptionalDecomposer: Decomposer[blueeyes.json.xschema.XOptional] = new Decomposer[blueeyes.json.xschema.XOptional] {
      def decompose(tvalue: blueeyes.json.xschema.XOptional): JValue = {
        JObject(
          JField("optionalType", blueeyes.json.xschema.Decomposers.XReferenceDecomposer.decompose(tvalue.optionalType)) :: Nil
        )
      }
    }
    
    implicit val XTupleDecomposer: Decomposer[blueeyes.json.xschema.XTuple] = new Decomposer[blueeyes.json.xschema.XTuple] {
      def decompose(tvalue: blueeyes.json.xschema.XTuple): JValue = {
        JObject(
          JField("types", blueeyes.json.xschema.DefaultDecomposers.ListDecomposer(blueeyes.json.xschema.Decomposers.XReferenceDecomposer).decompose(tvalue.types)) :: Nil
        )
      }
    }
    
    implicit val XDefinitionDecomposer: Decomposer[blueeyes.json.xschema.XDefinition] = new Decomposer[blueeyes.json.xschema.XDefinition] {
      def decompose(tvalue: blueeyes.json.xschema.XDefinition): JValue = {
        tvalue match {
          case x: blueeyes.json.xschema.XProduct => JObject(JField("XProduct", blueeyes.json.xschema.Decomposers.XProductDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XCoproduct => JObject(JField("XCoproduct", blueeyes.json.xschema.Decomposers.XCoproductDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XUnion => JObject(JField("XUnion", blueeyes.json.xschema.Decomposers.XUnionDecomposer.decompose(x)) :: Nil)
        }
      }
    }
    
    implicit val XMultitypeDecomposer: Decomposer[blueeyes.json.xschema.XMultitype] = new Decomposer[blueeyes.json.xschema.XMultitype] {
      def decompose(tvalue: blueeyes.json.xschema.XMultitype): JValue = {
        tvalue match {
          case x: blueeyes.json.xschema.XCoproduct => JObject(JField("XCoproduct", blueeyes.json.xschema.Decomposers.XCoproductDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XUnion => JObject(JField("XUnion", blueeyes.json.xschema.Decomposers.XUnionDecomposer.decompose(x)) :: Nil)
        }
      }
    }
    
    implicit val XFieldDecomposer: Decomposer[blueeyes.json.xschema.XField] = new Decomposer[blueeyes.json.xschema.XField] {
      def decompose(tvalue: blueeyes.json.xschema.XField): JValue = {
        tvalue match {
          case x: blueeyes.json.xschema.XRealField => JObject(JField("XRealField", blueeyes.json.xschema.Decomposers.XRealFieldDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XViewField => JObject(JField("XViewField", blueeyes.json.xschema.Decomposers.XViewFieldDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XConstantField => JObject(JField("XConstantField", blueeyes.json.xschema.Decomposers.XConstantFieldDecomposer.decompose(x)) :: Nil)
        }
      }
    }
    
    implicit val XProductDecomposer: Decomposer[blueeyes.json.xschema.XProduct] = new Decomposer[blueeyes.json.xschema.XProduct] {
      def decompose(tvalue: blueeyes.json.xschema.XProduct): JValue = {
        JObject(
          JField("name", blueeyes.json.xschema.DefaultDecomposers.StringDecomposer.decompose(tvalue.name)) ::
          JField("namespace", blueeyes.json.xschema.DefaultDecomposers.StringDecomposer.decompose(tvalue.namespace)) ::
          JField("properties", blueeyes.json.xschema.DefaultDecomposers.StringMapDecomposer(blueeyes.json.xschema.DefaultDecomposers.JValueDecomposer).decompose(tvalue.properties)) ::
          JField("terms", blueeyes.json.xschema.DefaultDecomposers.ListDecomposer(blueeyes.json.xschema.Decomposers.XFieldDecomposer).decompose(tvalue.terms)) :: Nil
        )
      }
    }
    
    implicit val XCoproductDecomposer: Decomposer[blueeyes.json.xschema.XCoproduct] = new Decomposer[blueeyes.json.xschema.XCoproduct] {
      def decompose(tvalue: blueeyes.json.xschema.XCoproduct): JValue = {
        JObject(
          JField("name", blueeyes.json.xschema.DefaultDecomposers.StringDecomposer.decompose(tvalue.name)) ::
          JField("namespace", blueeyes.json.xschema.DefaultDecomposers.StringDecomposer.decompose(tvalue.namespace)) ::
          JField("properties", blueeyes.json.xschema.DefaultDecomposers.StringMapDecomposer(blueeyes.json.xschema.DefaultDecomposers.JValueDecomposer).decompose(tvalue.properties)) ::
          JField("terms", blueeyes.json.xschema.DefaultDecomposers.ListDecomposer(blueeyes.json.xschema.Decomposers.XDefinitionRefDecomposer).decompose(tvalue.terms)) ::
          JField("default", blueeyes.json.xschema.DefaultDecomposers.JValueDecomposer.decompose(tvalue.default)) :: Nil
        )
      }
    }
    
    implicit val XUnionDecomposer: Decomposer[blueeyes.json.xschema.XUnion] = new Decomposer[blueeyes.json.xschema.XUnion] {
      def decompose(tvalue: blueeyes.json.xschema.XUnion): JValue = {
        JObject(
          JField("name", blueeyes.json.xschema.DefaultDecomposers.StringDecomposer.decompose(tvalue.name)) ::
          JField("namespace", blueeyes.json.xschema.DefaultDecomposers.StringDecomposer.decompose(tvalue.namespace)) ::
          JField("properties", blueeyes.json.xschema.DefaultDecomposers.StringMapDecomposer(blueeyes.json.xschema.DefaultDecomposers.JValueDecomposer).decompose(tvalue.properties)) ::
          JField("terms", blueeyes.json.xschema.DefaultDecomposers.ListDecomposer(blueeyes.json.xschema.Decomposers.XReferenceDecomposer).decompose(tvalue.terms)) ::
          JField("default", blueeyes.json.xschema.DefaultDecomposers.JValueDecomposer.decompose(tvalue.default)) :: Nil
        )
      }
    }
    
    implicit val XConstantDecomposer: Decomposer[blueeyes.json.xschema.XConstant] = new Decomposer[blueeyes.json.xschema.XConstant] {
      def decompose(tvalue: blueeyes.json.xschema.XConstant): JValue = {
        JObject(
          JField("name", blueeyes.json.xschema.DefaultDecomposers.StringDecomposer.decompose(tvalue.name)) ::
          JField("namespace", blueeyes.json.xschema.DefaultDecomposers.StringDecomposer.decompose(tvalue.namespace)) ::
          JField("properties", blueeyes.json.xschema.DefaultDecomposers.StringMapDecomposer(blueeyes.json.xschema.DefaultDecomposers.JValueDecomposer).decompose(tvalue.properties)) ::
          JField("constantType", blueeyes.json.xschema.Decomposers.XReferenceDecomposer.decompose(tvalue.constantType)) ::
          JField("default", blueeyes.json.xschema.DefaultDecomposers.JValueDecomposer.decompose(tvalue.default)) :: Nil
        )
      }
    }
    
    implicit val XRealFieldDecomposer: Decomposer[blueeyes.json.xschema.XRealField] = new Decomposer[blueeyes.json.xschema.XRealField] {
      def decompose(tvalue: blueeyes.json.xschema.XRealField): JValue = {
        JObject(
          JField("name", blueeyes.json.xschema.DefaultDecomposers.StringDecomposer.decompose(tvalue.name)) ::
          JField("properties", blueeyes.json.xschema.DefaultDecomposers.StringMapDecomposer(blueeyes.json.xschema.DefaultDecomposers.JValueDecomposer).decompose(tvalue.properties)) ::
          JField("fieldType", blueeyes.json.xschema.Decomposers.XReferenceDecomposer.decompose(tvalue.fieldType)) ::
          JField("default", blueeyes.json.xschema.DefaultDecomposers.JValueDecomposer.decompose(tvalue.default)) ::
          JField("order", blueeyes.json.xschema.Decomposers.XOrderDecomposer.decompose(tvalue.order)) :: Nil
        )
      }
    }
    
    implicit val XViewFieldDecomposer: Decomposer[blueeyes.json.xschema.XViewField] = new Decomposer[blueeyes.json.xschema.XViewField] {
      def decompose(tvalue: blueeyes.json.xschema.XViewField): JValue = {
        JObject(
          JField("name", blueeyes.json.xschema.DefaultDecomposers.StringDecomposer.decompose(tvalue.name)) ::
          JField("properties", blueeyes.json.xschema.DefaultDecomposers.StringMapDecomposer(blueeyes.json.xschema.DefaultDecomposers.JValueDecomposer).decompose(tvalue.properties)) ::
          JField("fieldType", blueeyes.json.xschema.Decomposers.XReferenceDecomposer.decompose(tvalue.fieldType)) :: Nil
        )
      }
    }
    
    implicit val XConstantFieldDecomposer: Decomposer[blueeyes.json.xschema.XConstantField] = new Decomposer[blueeyes.json.xschema.XConstantField] {
      def decompose(tvalue: blueeyes.json.xschema.XConstantField): JValue = {
        JObject(
          JField("name", blueeyes.json.xschema.DefaultDecomposers.StringDecomposer.decompose(tvalue.name)) ::
          JField("properties", blueeyes.json.xschema.DefaultDecomposers.StringMapDecomposer(blueeyes.json.xschema.DefaultDecomposers.JValueDecomposer).decompose(tvalue.properties)) ::
          JField("fieldType", blueeyes.json.xschema.Decomposers.XReferenceDecomposer.decompose(tvalue.fieldType)) ::
          JField("default", blueeyes.json.xschema.DefaultDecomposers.JValueDecomposer.decompose(tvalue.default)) :: Nil
        )
      }
    }
    
    implicit val XOrderDecomposer: Decomposer[blueeyes.json.xschema.XOrder] = new Decomposer[blueeyes.json.xschema.XOrder] {
      def decompose(tvalue: blueeyes.json.xschema.XOrder): JValue = {
        tvalue match {
          case x: blueeyes.json.xschema.XOrderAscending.type => JObject(JField("XOrderAscending", blueeyes.json.xschema.Decomposers.XOrderAscendingDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XOrderDescending.type => JObject(JField("XOrderDescending", blueeyes.json.xschema.Decomposers.XOrderDescendingDecomposer.decompose(x)) :: Nil)
          case x: blueeyes.json.xschema.XOrderIgnore.type => JObject(JField("XOrderIgnore", blueeyes.json.xschema.Decomposers.XOrderIgnoreDecomposer.decompose(x)) :: Nil)
        }
      }
    }
    
    implicit val XOrderAscendingDecomposer: Decomposer[blueeyes.json.xschema.XOrderAscending.type] = new Decomposer[blueeyes.json.xschema.XOrderAscending.type] {
      def decompose(tvalue: blueeyes.json.xschema.XOrderAscending.type): JValue = {
        JObject(
           Nil
        )
      }
    }
    
    implicit val XOrderDescendingDecomposer: Decomposer[blueeyes.json.xschema.XOrderDescending.type] = new Decomposer[blueeyes.json.xschema.XOrderDescending.type] {
      def decompose(tvalue: blueeyes.json.xschema.XOrderDescending.type): JValue = {
        JObject(
           Nil
        )
      }
    }
    
    implicit val XOrderIgnoreDecomposer: Decomposer[blueeyes.json.xschema.XOrderIgnore.type] = new Decomposer[blueeyes.json.xschema.XOrderIgnore.type] {
      def decompose(tvalue: blueeyes.json.xschema.XOrderIgnore.type): JValue = {
        JObject(
           Nil
        )
      }
    }
  }
  object Decomposers extends Decomposers
  
  object Serialization extends Decomposers with Extractors with SerializationImplicits {
    
  }
  
  object Constants {
    import Serialization._
    
    
  }
}