// These tests were auto-generated by Lift Json XSchema - do not edit
package blueeyes.json.serialization {
  import _root_.org.specs2.mutable.Specification

  import blueeyes.json.JsonParser._
  import blueeyes.json.JsonAST._
  
  import blueeyes.json.serialization.DefaultSerialization._
  
  import blueeyes.json.serialization.Serialization._
  
  object ExampleProductData {
    lazy val ExampleXRoot: blueeyes.json.serialization.XRoot = JObject(Nil).deserialize[blueeyes.json.serialization.XRoot]
    
    lazy val ExampleXDefinitionRef: blueeyes.json.serialization.XDefinitionRef = JObject(Nil).deserialize[blueeyes.json.serialization.XDefinitionRef]
    
    lazy val ExampleXBoolean: blueeyes.json.serialization.XBoolean.type = blueeyes.json.serialization.Extractors.XBooleanExtractor.extract(JObject(Nil))
    
    lazy val ExampleXInt: blueeyes.json.serialization.XInt.type = blueeyes.json.serialization.Extractors.XIntExtractor.extract(JObject(Nil))
    
    lazy val ExampleXLong: blueeyes.json.serialization.XLong.type = blueeyes.json.serialization.Extractors.XLongExtractor.extract(JObject(Nil))
    
    lazy val ExampleXFloat: blueeyes.json.serialization.XFloat.type = blueeyes.json.serialization.Extractors.XFloatExtractor.extract(JObject(Nil))
    
    lazy val ExampleXDouble: blueeyes.json.serialization.XDouble.type = blueeyes.json.serialization.Extractors.XDoubleExtractor.extract(JObject(Nil))
    
    lazy val ExampleXString: blueeyes.json.serialization.XString.type = blueeyes.json.serialization.Extractors.XStringExtractor.extract(JObject(Nil))
    
    lazy val ExampleXJSON: blueeyes.json.serialization.XJSON.type = blueeyes.json.serialization.Extractors.XJSONExtractor.extract(JObject(Nil))
    
    lazy val ExampleXDate: blueeyes.json.serialization.XDate.type = blueeyes.json.serialization.Extractors.XDateExtractor.extract(JObject(Nil))
    
    lazy val ExampleXList: blueeyes.json.serialization.XList = JObject(Nil).deserialize[blueeyes.json.serialization.XList]
    
    lazy val ExampleXSet: blueeyes.json.serialization.XSet = JObject(Nil).deserialize[blueeyes.json.serialization.XSet]
    
    lazy val ExampleXArray: blueeyes.json.serialization.XArray = JObject(Nil).deserialize[blueeyes.json.serialization.XArray]
    
    lazy val ExampleXMap: blueeyes.json.serialization.XMap = JObject(Nil).deserialize[blueeyes.json.serialization.XMap]
    
    lazy val ExampleXOptional: blueeyes.json.serialization.XOptional = JObject(Nil).deserialize[blueeyes.json.serialization.XOptional]
    
    lazy val ExampleXTuple: blueeyes.json.serialization.XTuple = JObject(Nil).deserialize[blueeyes.json.serialization.XTuple]
    
    lazy val ExampleXProduct: blueeyes.json.serialization.XProduct = JObject(Nil).deserialize[blueeyes.json.serialization.XProduct]
    
    lazy val ExampleXCoproduct: blueeyes.json.serialization.XCoproduct = JObject(Nil).deserialize[blueeyes.json.serialization.XCoproduct]
    
    lazy val ExampleXUnion: blueeyes.json.serialization.XUnion = JObject(Nil).deserialize[blueeyes.json.serialization.XUnion]
    
    lazy val ExampleXConstant: blueeyes.json.serialization.XConstant = JObject(Nil).deserialize[blueeyes.json.serialization.XConstant]
    
    lazy val ExampleXRealField: blueeyes.json.serialization.XRealField = JObject(Nil).deserialize[blueeyes.json.serialization.XRealField]
    
    lazy val ExampleXViewField: blueeyes.json.serialization.XViewField = JObject(Nil).deserialize[blueeyes.json.serialization.XViewField]
    
    lazy val ExampleXConstantField: blueeyes.json.serialization.XConstantField = JObject(Nil).deserialize[blueeyes.json.serialization.XConstantField]
    
    lazy val ExampleXOrderAscending: blueeyes.json.serialization.XOrderAscending.type = blueeyes.json.serialization.Extractors.XOrderAscendingExtractor.extract(JObject(Nil))
    
    lazy val ExampleXOrderDescending: blueeyes.json.serialization.XOrderDescending.type = blueeyes.json.serialization.Extractors.XOrderDescendingExtractor.extract(JObject(Nil))
    
    lazy val ExampleXOrderIgnore: blueeyes.json.serialization.XOrderIgnore.type = blueeyes.json.serialization.Extractors.XOrderIgnoreExtractor.extract(JObject(Nil))
  }
  object DataProductSerializationExamples extends Specification {
    "Deserialization of XRoot succeeds even when information is missing" in {
      ExampleProductData.ExampleXRoot.isInstanceOf[blueeyes.json.serialization.XRoot] must be_== (true)
    }
    "Serialization of XRoot has non-zero information content" in {
      ExampleProductData.ExampleXRoot.serialize must not be (JObject(Nil))
    }
  
    
    "Deserialization of XDefinitionRef succeeds even when information is missing" in {
      ExampleProductData.ExampleXDefinitionRef.isInstanceOf[blueeyes.json.serialization.XDefinitionRef] must be_== (true)
    }
    "Serialization of XDefinitionRef has non-zero information content" in {
      ExampleProductData.ExampleXDefinitionRef.serialize must not be (JObject(Nil))
    }
  
    
    "Deserialization of XBoolean succeeds even when information is missing" in {
      ExampleProductData.ExampleXBoolean.isInstanceOf[blueeyes.json.serialization.XBoolean.type] must be_== (true)
    }
    "Serialization of XBoolean has non-zero information content" in {
      Decomposers.XBooleanDecomposer.decompose(ExampleProductData.ExampleXBoolean) must not be (JObject(Nil))
    }
    
    "Deserialization of XInt succeeds even when information is missing" in {
      ExampleProductData.ExampleXInt.isInstanceOf[blueeyes.json.serialization.XInt.type] must be_== (true)
    }
    "Serialization of XInt has non-zero information content" in {
      Decomposers.XIntDecomposer.decompose(ExampleProductData.ExampleXInt) must not be (JObject(Nil))
    }
    
    "Deserialization of XLong succeeds even when information is missing" in {
      ExampleProductData.ExampleXLong.isInstanceOf[blueeyes.json.serialization.XLong.type] must be_== (true)
    }
    "Serialization of XLong has non-zero information content" in {
      Decomposers.XLongDecomposer.decompose(ExampleProductData.ExampleXLong) must not be (JObject(Nil))
    }
    
    "Deserialization of XFloat succeeds even when information is missing" in {
      ExampleProductData.ExampleXFloat.isInstanceOf[blueeyes.json.serialization.XFloat.type] must be_== (true)
    }
    "Serialization of XFloat has non-zero information content" in {
      Decomposers.XFloatDecomposer.decompose(ExampleProductData.ExampleXFloat) must not be (JObject(Nil))
    }
    
    "Deserialization of XDouble succeeds even when information is missing" in {
      ExampleProductData.ExampleXDouble.isInstanceOf[blueeyes.json.serialization.XDouble.type] must be_== (true)
    }
    "Serialization of XDouble has non-zero information content" in {
      Decomposers.XDoubleDecomposer.decompose(ExampleProductData.ExampleXDouble) must not be (JObject(Nil))
    }
    
    "Deserialization of XString succeeds even when information is missing" in {
      ExampleProductData.ExampleXString.isInstanceOf[blueeyes.json.serialization.XString.type] must be_== (true)
    }
    "Serialization of XString has non-zero information content" in {
      Decomposers.XStringDecomposer.decompose(ExampleProductData.ExampleXString) must not be (JObject(Nil))
    }
    
    "Deserialization of XJSON succeeds even when information is missing" in {
      ExampleProductData.ExampleXJSON.isInstanceOf[blueeyes.json.serialization.XJSON.type] must be_== (true)
    }
    "Serialization of XJSON has non-zero information content" in {
      Decomposers.XJSONDecomposer.decompose(ExampleProductData.ExampleXJSON) must not be (JObject(Nil))
    }
    
    "Deserialization of XDate succeeds even when information is missing" in {
      ExampleProductData.ExampleXDate.isInstanceOf[blueeyes.json.serialization.XDate.type] must be_== (true)
    }
    "Serialization of XDate has non-zero information content" in {
      Decomposers.XDateDecomposer.decompose(ExampleProductData.ExampleXDate) must not be (JObject(Nil))
    }
    
    "Deserialization of XList succeeds even when information is missing" in {
      ExampleProductData.ExampleXList.isInstanceOf[blueeyes.json.serialization.XList] must be_== (true)
    }
    "Serialization of XList has non-zero information content" in {
      ExampleProductData.ExampleXList.serialize must not be (JObject(Nil))
    }
  
    
    "Deserialization of XSet succeeds even when information is missing" in {
      ExampleProductData.ExampleXSet.isInstanceOf[blueeyes.json.serialization.XSet] must be_== (true)
    }
    "Serialization of XSet has non-zero information content" in {
      ExampleProductData.ExampleXSet.serialize must not be (JObject(Nil))
    }
  
    
    "Deserialization of XArray succeeds even when information is missing" in {
      ExampleProductData.ExampleXArray.isInstanceOf[blueeyes.json.serialization.XArray] must be_== (true)
    }
    "Serialization of XArray has non-zero information content" in {
      ExampleProductData.ExampleXArray.serialize must not be (JObject(Nil))
    }
  
    
    "Deserialization of XMap succeeds even when information is missing" in {
      ExampleProductData.ExampleXMap.isInstanceOf[blueeyes.json.serialization.XMap] must be_== (true)
    }
    "Serialization of XMap has non-zero information content" in {
      ExampleProductData.ExampleXMap.serialize must not be (JObject(Nil))
    }
  
    
    "Deserialization of XOptional succeeds even when information is missing" in {
      ExampleProductData.ExampleXOptional.isInstanceOf[blueeyes.json.serialization.XOptional] must be_== (true)
    }
    "Serialization of XOptional has non-zero information content" in {
      ExampleProductData.ExampleXOptional.serialize must not be (JObject(Nil))
    }
  
    
    "Deserialization of XTuple succeeds even when information is missing" in {
      ExampleProductData.ExampleXTuple.isInstanceOf[blueeyes.json.serialization.XTuple] must be_== (true)
    }
    "Serialization of XTuple has non-zero information content" in {
      ExampleProductData.ExampleXTuple.serialize must not be (JObject(Nil))
    }
  
    
    "Deserialization of XProduct succeeds even when information is missing" in {
      ExampleProductData.ExampleXProduct.isInstanceOf[blueeyes.json.serialization.XProduct] must be_== (true)
    }
    "Serialization of XProduct has non-zero information content" in {
      ExampleProductData.ExampleXProduct.serialize must not be (JObject(Nil))
    }
  
    
    "Deserialization of XCoproduct succeeds even when information is missing" in {
      ExampleProductData.ExampleXCoproduct.isInstanceOf[blueeyes.json.serialization.XCoproduct] must be_== (true)
    }
    "Serialization of XCoproduct has non-zero information content" in {
      ExampleProductData.ExampleXCoproduct.serialize must not be (JObject(Nil))
    }
  
    
    "Deserialization of XUnion succeeds even when information is missing" in {
      ExampleProductData.ExampleXUnion.isInstanceOf[blueeyes.json.serialization.XUnion] must be_== (true)
    }
    "Serialization of XUnion has non-zero information content" in {
      ExampleProductData.ExampleXUnion.serialize must not be (JObject(Nil))
    }
  
    
    "Deserialization of XConstant succeeds even when information is missing" in {
      ExampleProductData.ExampleXConstant.isInstanceOf[blueeyes.json.serialization.XConstant] must be_== (true)
    }
    "Serialization of XConstant has non-zero information content" in {
      ExampleProductData.ExampleXConstant.serialize must not be (JObject(Nil))
    }
  
    
    "Deserialization of XRealField succeeds even when information is missing" in {
      ExampleProductData.ExampleXRealField.isInstanceOf[blueeyes.json.serialization.XRealField] must be_== (true)
    }
    "Serialization of XRealField has non-zero information content" in {
      ExampleProductData.ExampleXRealField.serialize must not be (JObject(Nil))
    }
  
    
    "Deserialization of XViewField succeeds even when information is missing" in {
      ExampleProductData.ExampleXViewField.isInstanceOf[blueeyes.json.serialization.XViewField] must be_== (true)
    }
    "Serialization of XViewField has non-zero information content" in {
      ExampleProductData.ExampleXViewField.serialize must not be (JObject(Nil))
    }
  
    
    "Deserialization of XConstantField succeeds even when information is missing" in {
      ExampleProductData.ExampleXConstantField.isInstanceOf[blueeyes.json.serialization.XConstantField] must be_== (true)
    }
    "Serialization of XConstantField has non-zero information content" in {
      ExampleProductData.ExampleXConstantField.serialize must not be (JObject(Nil))
    }
  
    
    "Deserialization of XOrderAscending succeeds even when information is missing" in {
      ExampleProductData.ExampleXOrderAscending.isInstanceOf[blueeyes.json.serialization.XOrderAscending.type] must be_== (true)
    }
    "Serialization of XOrderAscending has non-zero information content" in {
      Decomposers.XOrderAscendingDecomposer.decompose(ExampleProductData.ExampleXOrderAscending) must not be (JObject(Nil))
    }
    
    "Deserialization of XOrderDescending succeeds even when information is missing" in {
      ExampleProductData.ExampleXOrderDescending.isInstanceOf[blueeyes.json.serialization.XOrderDescending.type] must be_== (true)
    }
    "Serialization of XOrderDescending has non-zero information content" in {
      Decomposers.XOrderDescendingDecomposer.decompose(ExampleProductData.ExampleXOrderDescending) must not be (JObject(Nil))
    }
    
    "Deserialization of XOrderIgnore succeeds even when information is missing" in {
      ExampleProductData.ExampleXOrderIgnore.isInstanceOf[blueeyes.json.serialization.XOrderIgnore.type] must be_== (true)
    }
    "Serialization of XOrderIgnore has non-zero information content" in {
      Decomposers.XOrderIgnoreDecomposer.decompose(ExampleProductData.ExampleXOrderIgnore) must not be (JObject(Nil))
    }
  }
  object ExampleMultitypeData {
    lazy val ExampleXSchema: blueeyes.json.serialization.XSchema = JObject(Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXProduct: blueeyes.json.serialization.XSchema = JObject(JField("XProduct", blueeyes.json.serialization.Decomposers.XProductDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXProduct)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXCoproduct: blueeyes.json.serialization.XSchema = JObject(JField("XCoproduct", blueeyes.json.serialization.Decomposers.XCoproductDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXCoproduct)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXUnion: blueeyes.json.serialization.XSchema = JObject(JField("XUnion", blueeyes.json.serialization.Decomposers.XUnionDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXUnion)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXBoolean: blueeyes.json.serialization.XSchema = JObject(JField("XBoolean", blueeyes.json.serialization.Decomposers.XBooleanDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXBoolean)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXInt: blueeyes.json.serialization.XSchema = JObject(JField("XInt", blueeyes.json.serialization.Decomposers.XIntDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXInt)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXLong: blueeyes.json.serialization.XSchema = JObject(JField("XLong", blueeyes.json.serialization.Decomposers.XLongDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXLong)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXFloat: blueeyes.json.serialization.XSchema = JObject(JField("XFloat", blueeyes.json.serialization.Decomposers.XFloatDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXFloat)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXDouble: blueeyes.json.serialization.XSchema = JObject(JField("XDouble", blueeyes.json.serialization.Decomposers.XDoubleDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXDouble)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXString: blueeyes.json.serialization.XSchema = JObject(JField("XString", blueeyes.json.serialization.Decomposers.XStringDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXString)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXJSON: blueeyes.json.serialization.XSchema = JObject(JField("XJSON", blueeyes.json.serialization.Decomposers.XJSONDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXJSON)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXDate: blueeyes.json.serialization.XSchema = JObject(JField("XDate", blueeyes.json.serialization.Decomposers.XDateDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXDate)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXList: blueeyes.json.serialization.XSchema = JObject(JField("XList", blueeyes.json.serialization.Decomposers.XListDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXList)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXSet: blueeyes.json.serialization.XSchema = JObject(JField("XSet", blueeyes.json.serialization.Decomposers.XSetDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXSet)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXArray: blueeyes.json.serialization.XSchema = JObject(JField("XArray", blueeyes.json.serialization.Decomposers.XArrayDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXArray)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXMap: blueeyes.json.serialization.XSchema = JObject(JField("XMap", blueeyes.json.serialization.Decomposers.XMapDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXMap)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXOptional: blueeyes.json.serialization.XSchema = JObject(JField("XOptional", blueeyes.json.serialization.Decomposers.XOptionalDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXOptional)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXTuple: blueeyes.json.serialization.XSchema = JObject(JField("XTuple", blueeyes.json.serialization.Decomposers.XTupleDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXTuple)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXDefinitionRef: blueeyes.json.serialization.XSchema = JObject(JField("XDefinitionRef", blueeyes.json.serialization.Decomposers.XDefinitionRefDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXDefinitionRef)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXRealField: blueeyes.json.serialization.XSchema = JObject(JField("XRealField", blueeyes.json.serialization.Decomposers.XRealFieldDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXRealField)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXViewField: blueeyes.json.serialization.XSchema = JObject(JField("XViewField", blueeyes.json.serialization.Decomposers.XViewFieldDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXViewField)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXConstantField: blueeyes.json.serialization.XSchema = JObject(JField("XConstantField", blueeyes.json.serialization.Decomposers.XConstantFieldDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXConstantField)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    lazy val ExampleXSchemaFromXConstant: blueeyes.json.serialization.XSchema = JObject(JField("XConstant", blueeyes.json.serialization.Decomposers.XConstantDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXConstant)) :: Nil).deserialize[blueeyes.json.serialization.XSchema]
    
    lazy val ExampleXReference: blueeyes.json.serialization.XReference = JObject(Nil).deserialize[blueeyes.json.serialization.XReference]
    lazy val ExampleXReferenceFromXBoolean: blueeyes.json.serialization.XReference = JObject(JField("XBoolean", blueeyes.json.serialization.Decomposers.XBooleanDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXBoolean)) :: Nil).deserialize[blueeyes.json.serialization.XReference]
    lazy val ExampleXReferenceFromXInt: blueeyes.json.serialization.XReference = JObject(JField("XInt", blueeyes.json.serialization.Decomposers.XIntDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXInt)) :: Nil).deserialize[blueeyes.json.serialization.XReference]
    lazy val ExampleXReferenceFromXLong: blueeyes.json.serialization.XReference = JObject(JField("XLong", blueeyes.json.serialization.Decomposers.XLongDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXLong)) :: Nil).deserialize[blueeyes.json.serialization.XReference]
    lazy val ExampleXReferenceFromXFloat: blueeyes.json.serialization.XReference = JObject(JField("XFloat", blueeyes.json.serialization.Decomposers.XFloatDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXFloat)) :: Nil).deserialize[blueeyes.json.serialization.XReference]
    lazy val ExampleXReferenceFromXDouble: blueeyes.json.serialization.XReference = JObject(JField("XDouble", blueeyes.json.serialization.Decomposers.XDoubleDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXDouble)) :: Nil).deserialize[blueeyes.json.serialization.XReference]
    lazy val ExampleXReferenceFromXString: blueeyes.json.serialization.XReference = JObject(JField("XString", blueeyes.json.serialization.Decomposers.XStringDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXString)) :: Nil).deserialize[blueeyes.json.serialization.XReference]
    lazy val ExampleXReferenceFromXJSON: blueeyes.json.serialization.XReference = JObject(JField("XJSON", blueeyes.json.serialization.Decomposers.XJSONDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXJSON)) :: Nil).deserialize[blueeyes.json.serialization.XReference]
    lazy val ExampleXReferenceFromXDate: blueeyes.json.serialization.XReference = JObject(JField("XDate", blueeyes.json.serialization.Decomposers.XDateDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXDate)) :: Nil).deserialize[blueeyes.json.serialization.XReference]
    lazy val ExampleXReferenceFromXList: blueeyes.json.serialization.XReference = JObject(JField("XList", blueeyes.json.serialization.Decomposers.XListDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXList)) :: Nil).deserialize[blueeyes.json.serialization.XReference]
    lazy val ExampleXReferenceFromXSet: blueeyes.json.serialization.XReference = JObject(JField("XSet", blueeyes.json.serialization.Decomposers.XSetDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXSet)) :: Nil).deserialize[blueeyes.json.serialization.XReference]
    lazy val ExampleXReferenceFromXArray: blueeyes.json.serialization.XReference = JObject(JField("XArray", blueeyes.json.serialization.Decomposers.XArrayDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXArray)) :: Nil).deserialize[blueeyes.json.serialization.XReference]
    lazy val ExampleXReferenceFromXMap: blueeyes.json.serialization.XReference = JObject(JField("XMap", blueeyes.json.serialization.Decomposers.XMapDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXMap)) :: Nil).deserialize[blueeyes.json.serialization.XReference]
    lazy val ExampleXReferenceFromXOptional: blueeyes.json.serialization.XReference = JObject(JField("XOptional", blueeyes.json.serialization.Decomposers.XOptionalDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXOptional)) :: Nil).deserialize[blueeyes.json.serialization.XReference]
    lazy val ExampleXReferenceFromXTuple: blueeyes.json.serialization.XReference = JObject(JField("XTuple", blueeyes.json.serialization.Decomposers.XTupleDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXTuple)) :: Nil).deserialize[blueeyes.json.serialization.XReference]
    lazy val ExampleXReferenceFromXDefinitionRef: blueeyes.json.serialization.XReference = JObject(JField("XDefinitionRef", blueeyes.json.serialization.Decomposers.XDefinitionRefDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXDefinitionRef)) :: Nil).deserialize[blueeyes.json.serialization.XReference]
    
    lazy val ExampleXPrimitiveRef: blueeyes.json.serialization.XPrimitiveRef = JObject(Nil).deserialize[blueeyes.json.serialization.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXBoolean: blueeyes.json.serialization.XPrimitiveRef = JObject(JField("XBoolean", blueeyes.json.serialization.Decomposers.XBooleanDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXBoolean)) :: Nil).deserialize[blueeyes.json.serialization.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXInt: blueeyes.json.serialization.XPrimitiveRef = JObject(JField("XInt", blueeyes.json.serialization.Decomposers.XIntDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXInt)) :: Nil).deserialize[blueeyes.json.serialization.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXLong: blueeyes.json.serialization.XPrimitiveRef = JObject(JField("XLong", blueeyes.json.serialization.Decomposers.XLongDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXLong)) :: Nil).deserialize[blueeyes.json.serialization.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXFloat: blueeyes.json.serialization.XPrimitiveRef = JObject(JField("XFloat", blueeyes.json.serialization.Decomposers.XFloatDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXFloat)) :: Nil).deserialize[blueeyes.json.serialization.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXDouble: blueeyes.json.serialization.XPrimitiveRef = JObject(JField("XDouble", blueeyes.json.serialization.Decomposers.XDoubleDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXDouble)) :: Nil).deserialize[blueeyes.json.serialization.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXString: blueeyes.json.serialization.XPrimitiveRef = JObject(JField("XString", blueeyes.json.serialization.Decomposers.XStringDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXString)) :: Nil).deserialize[blueeyes.json.serialization.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXJSON: blueeyes.json.serialization.XPrimitiveRef = JObject(JField("XJSON", blueeyes.json.serialization.Decomposers.XJSONDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXJSON)) :: Nil).deserialize[blueeyes.json.serialization.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXDate: blueeyes.json.serialization.XPrimitiveRef = JObject(JField("XDate", blueeyes.json.serialization.Decomposers.XDateDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXDate)) :: Nil).deserialize[blueeyes.json.serialization.XPrimitiveRef]
    
    lazy val ExampleXContainerRef: blueeyes.json.serialization.XContainerRef = JObject(Nil).deserialize[blueeyes.json.serialization.XContainerRef]
    lazy val ExampleXContainerRefFromXList: blueeyes.json.serialization.XContainerRef = JObject(JField("XList", blueeyes.json.serialization.Decomposers.XListDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXList)) :: Nil).deserialize[blueeyes.json.serialization.XContainerRef]
    lazy val ExampleXContainerRefFromXSet: blueeyes.json.serialization.XContainerRef = JObject(JField("XSet", blueeyes.json.serialization.Decomposers.XSetDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXSet)) :: Nil).deserialize[blueeyes.json.serialization.XContainerRef]
    lazy val ExampleXContainerRefFromXArray: blueeyes.json.serialization.XContainerRef = JObject(JField("XArray", blueeyes.json.serialization.Decomposers.XArrayDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXArray)) :: Nil).deserialize[blueeyes.json.serialization.XContainerRef]
    lazy val ExampleXContainerRefFromXMap: blueeyes.json.serialization.XContainerRef = JObject(JField("XMap", blueeyes.json.serialization.Decomposers.XMapDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXMap)) :: Nil).deserialize[blueeyes.json.serialization.XContainerRef]
    lazy val ExampleXContainerRefFromXOptional: blueeyes.json.serialization.XContainerRef = JObject(JField("XOptional", blueeyes.json.serialization.Decomposers.XOptionalDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXOptional)) :: Nil).deserialize[blueeyes.json.serialization.XContainerRef]
    lazy val ExampleXContainerRefFromXTuple: blueeyes.json.serialization.XContainerRef = JObject(JField("XTuple", blueeyes.json.serialization.Decomposers.XTupleDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXTuple)) :: Nil).deserialize[blueeyes.json.serialization.XContainerRef]
    
    lazy val ExampleXCollection: blueeyes.json.serialization.XCollection = JObject(Nil).deserialize[blueeyes.json.serialization.XCollection]
    lazy val ExampleXCollectionFromXList: blueeyes.json.serialization.XCollection = JObject(JField("XList", blueeyes.json.serialization.Decomposers.XListDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXList)) :: Nil).deserialize[blueeyes.json.serialization.XCollection]
    lazy val ExampleXCollectionFromXSet: blueeyes.json.serialization.XCollection = JObject(JField("XSet", blueeyes.json.serialization.Decomposers.XSetDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXSet)) :: Nil).deserialize[blueeyes.json.serialization.XCollection]
    lazy val ExampleXCollectionFromXArray: blueeyes.json.serialization.XCollection = JObject(JField("XArray", blueeyes.json.serialization.Decomposers.XArrayDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXArray)) :: Nil).deserialize[blueeyes.json.serialization.XCollection]
    
    lazy val ExampleXDefinition: blueeyes.json.serialization.XDefinition = JObject(Nil).deserialize[blueeyes.json.serialization.XDefinition]
    lazy val ExampleXDefinitionFromXProduct: blueeyes.json.serialization.XDefinition = JObject(JField("XProduct", blueeyes.json.serialization.Decomposers.XProductDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXProduct)) :: Nil).deserialize[blueeyes.json.serialization.XDefinition]
    lazy val ExampleXDefinitionFromXCoproduct: blueeyes.json.serialization.XDefinition = JObject(JField("XCoproduct", blueeyes.json.serialization.Decomposers.XCoproductDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXCoproduct)) :: Nil).deserialize[blueeyes.json.serialization.XDefinition]
    lazy val ExampleXDefinitionFromXUnion: blueeyes.json.serialization.XDefinition = JObject(JField("XUnion", blueeyes.json.serialization.Decomposers.XUnionDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXUnion)) :: Nil).deserialize[blueeyes.json.serialization.XDefinition]
    
    lazy val ExampleXMultitype: blueeyes.json.serialization.XMultitype = JObject(Nil).deserialize[blueeyes.json.serialization.XMultitype]
    lazy val ExampleXMultitypeFromXCoproduct: blueeyes.json.serialization.XMultitype = JObject(JField("XCoproduct", blueeyes.json.serialization.Decomposers.XCoproductDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXCoproduct)) :: Nil).deserialize[blueeyes.json.serialization.XMultitype]
    lazy val ExampleXMultitypeFromXUnion: blueeyes.json.serialization.XMultitype = JObject(JField("XUnion", blueeyes.json.serialization.Decomposers.XUnionDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXUnion)) :: Nil).deserialize[blueeyes.json.serialization.XMultitype]
    
    lazy val ExampleXField: blueeyes.json.serialization.XField = JObject(Nil).deserialize[blueeyes.json.serialization.XField]
    lazy val ExampleXFieldFromXRealField: blueeyes.json.serialization.XField = JObject(JField("XRealField", blueeyes.json.serialization.Decomposers.XRealFieldDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXRealField)) :: Nil).deserialize[blueeyes.json.serialization.XField]
    lazy val ExampleXFieldFromXViewField: blueeyes.json.serialization.XField = JObject(JField("XViewField", blueeyes.json.serialization.Decomposers.XViewFieldDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXViewField)) :: Nil).deserialize[blueeyes.json.serialization.XField]
    lazy val ExampleXFieldFromXConstantField: blueeyes.json.serialization.XField = JObject(JField("XConstantField", blueeyes.json.serialization.Decomposers.XConstantFieldDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXConstantField)) :: Nil).deserialize[blueeyes.json.serialization.XField]
    
    lazy val ExampleXOrder: blueeyes.json.serialization.XOrder = JObject(Nil).deserialize[blueeyes.json.serialization.XOrder]
    lazy val ExampleXOrderFromXOrderAscending: blueeyes.json.serialization.XOrder = JObject(JField("XOrderAscending", blueeyes.json.serialization.Decomposers.XOrderAscendingDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXOrderAscending)) :: Nil).deserialize[blueeyes.json.serialization.XOrder]
    lazy val ExampleXOrderFromXOrderDescending: blueeyes.json.serialization.XOrder = JObject(JField("XOrderDescending", blueeyes.json.serialization.Decomposers.XOrderDescendingDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXOrderDescending)) :: Nil).deserialize[blueeyes.json.serialization.XOrder]
    lazy val ExampleXOrderFromXOrderIgnore: blueeyes.json.serialization.XOrder = JObject(JField("XOrderIgnore", blueeyes.json.serialization.Decomposers.XOrderIgnoreDecomposer.decompose(blueeyes.json.serialization.ExampleProductData.ExampleXOrderIgnore)) :: Nil).deserialize[blueeyes.json.serialization.XOrder]
  }
  object DataCoproductSerializationExamples extends Specification {
    "Deserialization of XSchema succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXSchema.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchema.serialize must not be (JObject(Nil))
    }
  
    "Deserialization of XSchema (from XProduct) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXProduct.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XProduct) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXProduct.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XCoproduct) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXCoproduct.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XCoproduct) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXCoproduct.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XUnion) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXUnion.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XUnion) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXUnion.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XBoolean) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXBoolean.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XBoolean) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXBoolean.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XInt) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXInt.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XInt) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXInt.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XLong) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXLong.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XLong) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXLong.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XFloat) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXFloat.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XFloat) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXFloat.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XDouble) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXDouble.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XDouble) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXDouble.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XString) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXString.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XString) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXString.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XJSON) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXJSON.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XJSON) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXJSON.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XDate) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXDate.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XDate) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXDate.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XList) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXList.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XList) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXList.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XSet) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXSet.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XSet) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXSet.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XArray) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXArray.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XArray) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXArray.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XMap) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXMap.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XMap) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXMap.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XOptional) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXOptional.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XOptional) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXOptional.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XTuple) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXTuple.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XTuple) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXTuple.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XDefinitionRef) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXDefinitionRef.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XDefinitionRef) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXDefinitionRef.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XRealField) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXRealField.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XRealField) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXRealField.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XViewField) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXViewField.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XViewField) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXViewField.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XConstantField) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXConstantField.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XConstantField) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXConstantField.serialize must not be (JObject(Nil))
    }
    "Deserialization of XSchema (from XConstant) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXConstant.isInstanceOf[blueeyes.json.serialization.XSchema] must be_== (true)
    }            
    "Serialization of XSchema (from XConstant) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXConstant.serialize must not be (JObject(Nil))
    }
    
    "Deserialization of XReference succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXReference.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference has non-zero information content" in {
      ExampleMultitypeData.ExampleXReference.serialize must not be (JObject(Nil))
    }
  
    "Deserialization of XReference (from XBoolean) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXBoolean.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference (from XBoolean) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXBoolean.serialize must not be (JObject(Nil))
    }
    "Deserialization of XReference (from XInt) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXInt.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference (from XInt) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXInt.serialize must not be (JObject(Nil))
    }
    "Deserialization of XReference (from XLong) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXLong.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference (from XLong) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXLong.serialize must not be (JObject(Nil))
    }
    "Deserialization of XReference (from XFloat) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXFloat.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference (from XFloat) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXFloat.serialize must not be (JObject(Nil))
    }
    "Deserialization of XReference (from XDouble) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXDouble.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference (from XDouble) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXDouble.serialize must not be (JObject(Nil))
    }
    "Deserialization of XReference (from XString) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXString.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference (from XString) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXString.serialize must not be (JObject(Nil))
    }
    "Deserialization of XReference (from XJSON) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXJSON.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference (from XJSON) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXJSON.serialize must not be (JObject(Nil))
    }
    "Deserialization of XReference (from XDate) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXDate.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference (from XDate) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXDate.serialize must not be (JObject(Nil))
    }
    "Deserialization of XReference (from XList) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXList.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference (from XList) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXList.serialize must not be (JObject(Nil))
    }
    "Deserialization of XReference (from XSet) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXSet.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference (from XSet) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXSet.serialize must not be (JObject(Nil))
    }
    "Deserialization of XReference (from XArray) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXArray.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference (from XArray) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXArray.serialize must not be (JObject(Nil))
    }
    "Deserialization of XReference (from XMap) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXMap.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference (from XMap) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXMap.serialize must not be (JObject(Nil))
    }
    "Deserialization of XReference (from XOptional) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXOptional.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference (from XOptional) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXOptional.serialize must not be (JObject(Nil))
    }
    "Deserialization of XReference (from XTuple) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXTuple.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference (from XTuple) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXTuple.serialize must not be (JObject(Nil))
    }
    "Deserialization of XReference (from XDefinitionRef) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXDefinitionRef.isInstanceOf[blueeyes.json.serialization.XReference] must be_== (true)
    }            
    "Serialization of XReference (from XDefinitionRef) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXDefinitionRef.serialize must not be (JObject(Nil))
    }
    
    "Deserialization of XPrimitiveRef succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXPrimitiveRef.isInstanceOf[blueeyes.json.serialization.XPrimitiveRef] must be_== (true)
    }            
    "Serialization of XPrimitiveRef has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRef.serialize must not be (JObject(Nil))
    }
  
    "Deserialization of XPrimitiveRef (from XBoolean) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXBoolean.isInstanceOf[blueeyes.json.serialization.XPrimitiveRef] must be_== (true)
    }            
    "Serialization of XPrimitiveRef (from XBoolean) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXBoolean.serialize must not be (JObject(Nil))
    }
    "Deserialization of XPrimitiveRef (from XInt) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXInt.isInstanceOf[blueeyes.json.serialization.XPrimitiveRef] must be_== (true)
    }            
    "Serialization of XPrimitiveRef (from XInt) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXInt.serialize must not be (JObject(Nil))
    }
    "Deserialization of XPrimitiveRef (from XLong) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXLong.isInstanceOf[blueeyes.json.serialization.XPrimitiveRef] must be_== (true)
    }            
    "Serialization of XPrimitiveRef (from XLong) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXLong.serialize must not be (JObject(Nil))
    }
    "Deserialization of XPrimitiveRef (from XFloat) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXFloat.isInstanceOf[blueeyes.json.serialization.XPrimitiveRef] must be_== (true)
    }            
    "Serialization of XPrimitiveRef (from XFloat) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXFloat.serialize must not be (JObject(Nil))
    }
    "Deserialization of XPrimitiveRef (from XDouble) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXDouble.isInstanceOf[blueeyes.json.serialization.XPrimitiveRef] must be_== (true)
    }            
    "Serialization of XPrimitiveRef (from XDouble) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXDouble.serialize must not be (JObject(Nil))
    }
    "Deserialization of XPrimitiveRef (from XString) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXString.isInstanceOf[blueeyes.json.serialization.XPrimitiveRef] must be_== (true)
    }            
    "Serialization of XPrimitiveRef (from XString) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXString.serialize must not be (JObject(Nil))
    }
    "Deserialization of XPrimitiveRef (from XJSON) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXJSON.isInstanceOf[blueeyes.json.serialization.XPrimitiveRef] must be_== (true)
    }            
    "Serialization of XPrimitiveRef (from XJSON) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXJSON.serialize must not be (JObject(Nil))
    }
    "Deserialization of XPrimitiveRef (from XDate) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXDate.isInstanceOf[blueeyes.json.serialization.XPrimitiveRef] must be_== (true)
    }            
    "Serialization of XPrimitiveRef (from XDate) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXDate.serialize must not be (JObject(Nil))
    }
    
    "Deserialization of XContainerRef succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXContainerRef.isInstanceOf[blueeyes.json.serialization.XContainerRef] must be_== (true)
    }            
    "Serialization of XContainerRef has non-zero information content" in {
      ExampleMultitypeData.ExampleXContainerRef.serialize must not be (JObject(Nil))
    }
  
    "Deserialization of XContainerRef (from XList) succeeds" in {
      ExampleMultitypeData.ExampleXContainerRefFromXList.isInstanceOf[blueeyes.json.serialization.XContainerRef] must be_== (true)
    }            
    "Serialization of XContainerRef (from XList) has non-zero information content" in {
      ExampleMultitypeData.ExampleXContainerRefFromXList.serialize must not be (JObject(Nil))
    }
    "Deserialization of XContainerRef (from XSet) succeeds" in {
      ExampleMultitypeData.ExampleXContainerRefFromXSet.isInstanceOf[blueeyes.json.serialization.XContainerRef] must be_== (true)
    }            
    "Serialization of XContainerRef (from XSet) has non-zero information content" in {
      ExampleMultitypeData.ExampleXContainerRefFromXSet.serialize must not be (JObject(Nil))
    }
    "Deserialization of XContainerRef (from XArray) succeeds" in {
      ExampleMultitypeData.ExampleXContainerRefFromXArray.isInstanceOf[blueeyes.json.serialization.XContainerRef] must be_== (true)
    }            
    "Serialization of XContainerRef (from XArray) has non-zero information content" in {
      ExampleMultitypeData.ExampleXContainerRefFromXArray.serialize must not be (JObject(Nil))
    }
    "Deserialization of XContainerRef (from XMap) succeeds" in {
      ExampleMultitypeData.ExampleXContainerRefFromXMap.isInstanceOf[blueeyes.json.serialization.XContainerRef] must be_== (true)
    }            
    "Serialization of XContainerRef (from XMap) has non-zero information content" in {
      ExampleMultitypeData.ExampleXContainerRefFromXMap.serialize must not be (JObject(Nil))
    }
    "Deserialization of XContainerRef (from XOptional) succeeds" in {
      ExampleMultitypeData.ExampleXContainerRefFromXOptional.isInstanceOf[blueeyes.json.serialization.XContainerRef] must be_== (true)
    }            
    "Serialization of XContainerRef (from XOptional) has non-zero information content" in {
      ExampleMultitypeData.ExampleXContainerRefFromXOptional.serialize must not be (JObject(Nil))
    }
    "Deserialization of XContainerRef (from XTuple) succeeds" in {
      ExampleMultitypeData.ExampleXContainerRefFromXTuple.isInstanceOf[blueeyes.json.serialization.XContainerRef] must be_== (true)
    }            
    "Serialization of XContainerRef (from XTuple) has non-zero information content" in {
      ExampleMultitypeData.ExampleXContainerRefFromXTuple.serialize must not be (JObject(Nil))
    }
    
    "Deserialization of XCollection succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXCollection.isInstanceOf[blueeyes.json.serialization.XCollection] must be_== (true)
    }            
    "Serialization of XCollection has non-zero information content" in {
      ExampleMultitypeData.ExampleXCollection.serialize must not be (JObject(Nil))
    }
  
    "Deserialization of XCollection (from XList) succeeds" in {
      ExampleMultitypeData.ExampleXCollectionFromXList.isInstanceOf[blueeyes.json.serialization.XCollection] must be_== (true)
    }            
    "Serialization of XCollection (from XList) has non-zero information content" in {
      ExampleMultitypeData.ExampleXCollectionFromXList.serialize must not be (JObject(Nil))
    }
    "Deserialization of XCollection (from XSet) succeeds" in {
      ExampleMultitypeData.ExampleXCollectionFromXSet.isInstanceOf[blueeyes.json.serialization.XCollection] must be_== (true)
    }            
    "Serialization of XCollection (from XSet) has non-zero information content" in {
      ExampleMultitypeData.ExampleXCollectionFromXSet.serialize must not be (JObject(Nil))
    }
    "Deserialization of XCollection (from XArray) succeeds" in {
      ExampleMultitypeData.ExampleXCollectionFromXArray.isInstanceOf[blueeyes.json.serialization.XCollection] must be_== (true)
    }            
    "Serialization of XCollection (from XArray) has non-zero information content" in {
      ExampleMultitypeData.ExampleXCollectionFromXArray.serialize must not be (JObject(Nil))
    }
    
    "Deserialization of XDefinition succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXDefinition.isInstanceOf[blueeyes.json.serialization.XDefinition] must be_== (true)
    }            
    "Serialization of XDefinition has non-zero information content" in {
      ExampleMultitypeData.ExampleXDefinition.serialize must not be (JObject(Nil))
    }
  
    "Deserialization of XDefinition (from XProduct) succeeds" in {
      ExampleMultitypeData.ExampleXDefinitionFromXProduct.isInstanceOf[blueeyes.json.serialization.XDefinition] must be_== (true)
    }            
    "Serialization of XDefinition (from XProduct) has non-zero information content" in {
      ExampleMultitypeData.ExampleXDefinitionFromXProduct.serialize must not be (JObject(Nil))
    }
    "Deserialization of XDefinition (from XCoproduct) succeeds" in {
      ExampleMultitypeData.ExampleXDefinitionFromXCoproduct.isInstanceOf[blueeyes.json.serialization.XDefinition] must be_== (true)
    }            
    "Serialization of XDefinition (from XCoproduct) has non-zero information content" in {
      ExampleMultitypeData.ExampleXDefinitionFromXCoproduct.serialize must not be (JObject(Nil))
    }
    "Deserialization of XDefinition (from XUnion) succeeds" in {
      ExampleMultitypeData.ExampleXDefinitionFromXUnion.isInstanceOf[blueeyes.json.serialization.XDefinition] must be_== (true)
    }            
    "Serialization of XDefinition (from XUnion) has non-zero information content" in {
      ExampleMultitypeData.ExampleXDefinitionFromXUnion.serialize must not be (JObject(Nil))
    }
    
    "Deserialization of XMultitype succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXMultitype.isInstanceOf[blueeyes.json.serialization.XMultitype] must be_== (true)
    }            
    "Serialization of XMultitype has non-zero information content" in {
      ExampleMultitypeData.ExampleXMultitype.serialize must not be (JObject(Nil))
    }
  
    "Deserialization of XMultitype (from XCoproduct) succeeds" in {
      ExampleMultitypeData.ExampleXMultitypeFromXCoproduct.isInstanceOf[blueeyes.json.serialization.XMultitype] must be_== (true)
    }            
    "Serialization of XMultitype (from XCoproduct) has non-zero information content" in {
      ExampleMultitypeData.ExampleXMultitypeFromXCoproduct.serialize must not be (JObject(Nil))
    }
    "Deserialization of XMultitype (from XUnion) succeeds" in {
      ExampleMultitypeData.ExampleXMultitypeFromXUnion.isInstanceOf[blueeyes.json.serialization.XMultitype] must be_== (true)
    }            
    "Serialization of XMultitype (from XUnion) has non-zero information content" in {
      ExampleMultitypeData.ExampleXMultitypeFromXUnion.serialize must not be (JObject(Nil))
    }
    
    "Deserialization of XField succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXField.isInstanceOf[blueeyes.json.serialization.XField] must be_== (true)
    }            
    "Serialization of XField has non-zero information content" in {
      ExampleMultitypeData.ExampleXField.serialize must not be (JObject(Nil))
    }
  
    "Deserialization of XField (from XRealField) succeeds" in {
      ExampleMultitypeData.ExampleXFieldFromXRealField.isInstanceOf[blueeyes.json.serialization.XField] must be_== (true)
    }            
    "Serialization of XField (from XRealField) has non-zero information content" in {
      ExampleMultitypeData.ExampleXFieldFromXRealField.serialize must not be (JObject(Nil))
    }
    "Deserialization of XField (from XViewField) succeeds" in {
      ExampleMultitypeData.ExampleXFieldFromXViewField.isInstanceOf[blueeyes.json.serialization.XField] must be_== (true)
    }            
    "Serialization of XField (from XViewField) has non-zero information content" in {
      ExampleMultitypeData.ExampleXFieldFromXViewField.serialize must not be (JObject(Nil))
    }
    "Deserialization of XField (from XConstantField) succeeds" in {
      ExampleMultitypeData.ExampleXFieldFromXConstantField.isInstanceOf[blueeyes.json.serialization.XField] must be_== (true)
    }            
    "Serialization of XField (from XConstantField) has non-zero information content" in {
      ExampleMultitypeData.ExampleXFieldFromXConstantField.serialize must not be (JObject(Nil))
    }
    
    "Deserialization of XOrder succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXOrder.isInstanceOf[blueeyes.json.serialization.XOrder] must be_== (true)
    }            
    "Serialization of XOrder has non-zero information content" in {
      ExampleMultitypeData.ExampleXOrder.serialize must not be (JObject(Nil))
    }
  
    "Deserialization of XOrder (from XOrderAscending) succeeds" in {
      ExampleMultitypeData.ExampleXOrderFromXOrderAscending.isInstanceOf[blueeyes.json.serialization.XOrder] must be_== (true)
    }            
    "Serialization of XOrder (from XOrderAscending) has non-zero information content" in {
      ExampleMultitypeData.ExampleXOrderFromXOrderAscending.serialize must not be (JObject(Nil))
    }
    "Deserialization of XOrder (from XOrderDescending) succeeds" in {
      ExampleMultitypeData.ExampleXOrderFromXOrderDescending.isInstanceOf[blueeyes.json.serialization.XOrder] must be_== (true)
    }            
    "Serialization of XOrder (from XOrderDescending) has non-zero information content" in {
      ExampleMultitypeData.ExampleXOrderFromXOrderDescending.serialize must not be (JObject(Nil))
    }
    "Deserialization of XOrder (from XOrderIgnore) succeeds" in {
      ExampleMultitypeData.ExampleXOrderFromXOrderIgnore.isInstanceOf[blueeyes.json.serialization.XOrder] must be_== (true)
    }            
    "Serialization of XOrder (from XOrderIgnore) has non-zero information content" in {
      ExampleMultitypeData.ExampleXOrderFromXOrderIgnore.serialize must not be (JObject(Nil))
    }
  }
  object DataConstantsSerializationExamples extends Specification {
    
  }
}
