// These tests were auto-generated by Lift Json XSchema - do not edit
package blueeyes.json.xschema {
  import _root_.org.specs.Specification
  import _root_.org.specs.runner.{Runner, JUnit}
  
  import blueeyes.json.JsonParser._
  import blueeyes.json.JsonAST._
  
  import blueeyes.json.xschema.DefaultSerialization._
  
  import blueeyes.json.xschema.Serialization._
  import blueeyes.json.xschema.Constants._

  import blueeyes.json.xschema.{XSchema, XReference, XPrimitiveRef, XContainerRef, XCollection, XDefinition, XMultitype, XField, XOrder, XRoot, XDefinitionRef, XBoolean, XInt, XLong, XFloat, XDouble, XString, XJSON, XDate, XList, XSet, XArray, XMap, XOptional, XTuple, XProduct, XCoproduct, XUnion, XConstant, XRealField, XViewField, XConstantField, XOrderAscending, XOrderDescending, XOrderIgnore}
  
  object ExampleProductData {
    lazy val ExampleXRoot: blueeyes.json.xschema.XRoot = JObject(Nil).deserialize[blueeyes.json.xschema.XRoot]
    
    lazy val ExampleXDefinitionRef: blueeyes.json.xschema.XDefinitionRef = JObject(Nil).deserialize[blueeyes.json.xschema.XDefinitionRef]
    
    lazy val ExampleXBoolean: blueeyes.json.xschema.XBoolean.type = blueeyes.json.xschema.Extractors.XBooleanExtractor.extract(JObject(Nil))
    
    lazy val ExampleXInt: blueeyes.json.xschema.XInt.type = blueeyes.json.xschema.Extractors.XIntExtractor.extract(JObject(Nil))
    
    lazy val ExampleXLong: blueeyes.json.xschema.XLong.type = blueeyes.json.xschema.Extractors.XLongExtractor.extract(JObject(Nil))
    
    lazy val ExampleXFloat: blueeyes.json.xschema.XFloat.type = blueeyes.json.xschema.Extractors.XFloatExtractor.extract(JObject(Nil))
    
    lazy val ExampleXDouble: blueeyes.json.xschema.XDouble.type = blueeyes.json.xschema.Extractors.XDoubleExtractor.extract(JObject(Nil))
    
    lazy val ExampleXString: blueeyes.json.xschema.XString.type = blueeyes.json.xschema.Extractors.XStringExtractor.extract(JObject(Nil))
    
    lazy val ExampleXJSON: blueeyes.json.xschema.XJSON.type = blueeyes.json.xschema.Extractors.XJSONExtractor.extract(JObject(Nil))
    
    lazy val ExampleXDate: blueeyes.json.xschema.XDate.type = blueeyes.json.xschema.Extractors.XDateExtractor.extract(JObject(Nil))
    
    lazy val ExampleXList: blueeyes.json.xschema.XList = JObject(Nil).deserialize[blueeyes.json.xschema.XList]
    
    lazy val ExampleXSet: blueeyes.json.xschema.XSet = JObject(Nil).deserialize[blueeyes.json.xschema.XSet]
    
    lazy val ExampleXArray: blueeyes.json.xschema.XArray = JObject(Nil).deserialize[blueeyes.json.xschema.XArray]
    
    lazy val ExampleXMap: blueeyes.json.xschema.XMap = JObject(Nil).deserialize[blueeyes.json.xschema.XMap]
    
    lazy val ExampleXOptional: blueeyes.json.xschema.XOptional = JObject(Nil).deserialize[blueeyes.json.xschema.XOptional]
    
    lazy val ExampleXTuple: blueeyes.json.xschema.XTuple = JObject(Nil).deserialize[blueeyes.json.xschema.XTuple]
    
    lazy val ExampleXProduct: blueeyes.json.xschema.XProduct = JObject(Nil).deserialize[blueeyes.json.xschema.XProduct]
    
    lazy val ExampleXCoproduct: blueeyes.json.xschema.XCoproduct = JObject(Nil).deserialize[blueeyes.json.xschema.XCoproduct]
    
    lazy val ExampleXUnion: blueeyes.json.xschema.XUnion = JObject(Nil).deserialize[blueeyes.json.xschema.XUnion]
    
    lazy val ExampleXConstant: blueeyes.json.xschema.XConstant = JObject(Nil).deserialize[blueeyes.json.xschema.XConstant]
    
    lazy val ExampleXRealField: blueeyes.json.xschema.XRealField = JObject(Nil).deserialize[blueeyes.json.xschema.XRealField]
    
    lazy val ExampleXViewField: blueeyes.json.xschema.XViewField = JObject(Nil).deserialize[blueeyes.json.xschema.XViewField]
    
    lazy val ExampleXConstantField: blueeyes.json.xschema.XConstantField = JObject(Nil).deserialize[blueeyes.json.xschema.XConstantField]
    
    lazy val ExampleXOrderAscending: blueeyes.json.xschema.XOrderAscending.type = blueeyes.json.xschema.Extractors.XOrderAscendingExtractor.extract(JObject(Nil))
    
    lazy val ExampleXOrderDescending: blueeyes.json.xschema.XOrderDescending.type = blueeyes.json.xschema.Extractors.XOrderDescendingExtractor.extract(JObject(Nil))
    
    lazy val ExampleXOrderIgnore: blueeyes.json.xschema.XOrderIgnore.type = blueeyes.json.xschema.Extractors.XOrderIgnoreExtractor.extract(JObject(Nil))
  }
  class DataProductSerializationTest extends Runner(DataProductSerializationExamples) with JUnit
  object DataProductSerializationExamples extends Specification {
    "Deserialization of XRoot succeeds even when information is missing" in {
      ExampleProductData.ExampleXRoot.isInstanceOf[blueeyes.json.xschema.XRoot] must be (true)
    }
    "Serialization of XRoot has non-zero information content" in {
      ExampleProductData.ExampleXRoot.serialize mustNot be (JObject(Nil))
    }
  
    
    "Deserialization of XDefinitionRef succeeds even when information is missing" in {
      ExampleProductData.ExampleXDefinitionRef.isInstanceOf[blueeyes.json.xschema.XDefinitionRef] must be (true)
    }
    "Serialization of XDefinitionRef has non-zero information content" in {
      ExampleProductData.ExampleXDefinitionRef.serialize mustNot be (JObject(Nil))
    }
  
    
    "Deserialization of XBoolean succeeds even when information is missing" in {
      ExampleProductData.ExampleXBoolean.isInstanceOf[blueeyes.json.xschema.XBoolean.type] must be (true)
    }
    "Serialization of XBoolean has non-zero information content" in {
      Decomposers.XBooleanDecomposer.decompose(ExampleProductData.ExampleXBoolean) mustNot be (JObject(Nil))
    }
    
    "Deserialization of XInt succeeds even when information is missing" in {
      ExampleProductData.ExampleXInt.isInstanceOf[blueeyes.json.xschema.XInt.type] must be (true)
    }
    "Serialization of XInt has non-zero information content" in {
      Decomposers.XIntDecomposer.decompose(ExampleProductData.ExampleXInt) mustNot be (JObject(Nil))
    }
    
    "Deserialization of XLong succeeds even when information is missing" in {
      ExampleProductData.ExampleXLong.isInstanceOf[blueeyes.json.xschema.XLong.type] must be (true)
    }
    "Serialization of XLong has non-zero information content" in {
      Decomposers.XLongDecomposer.decompose(ExampleProductData.ExampleXLong) mustNot be (JObject(Nil))
    }
    
    "Deserialization of XFloat succeeds even when information is missing" in {
      ExampleProductData.ExampleXFloat.isInstanceOf[blueeyes.json.xschema.XFloat.type] must be (true)
    }
    "Serialization of XFloat has non-zero information content" in {
      Decomposers.XFloatDecomposer.decompose(ExampleProductData.ExampleXFloat) mustNot be (JObject(Nil))
    }
    
    "Deserialization of XDouble succeeds even when information is missing" in {
      ExampleProductData.ExampleXDouble.isInstanceOf[blueeyes.json.xschema.XDouble.type] must be (true)
    }
    "Serialization of XDouble has non-zero information content" in {
      Decomposers.XDoubleDecomposer.decompose(ExampleProductData.ExampleXDouble) mustNot be (JObject(Nil))
    }
    
    "Deserialization of XString succeeds even when information is missing" in {
      ExampleProductData.ExampleXString.isInstanceOf[blueeyes.json.xschema.XString.type] must be (true)
    }
    "Serialization of XString has non-zero information content" in {
      Decomposers.XStringDecomposer.decompose(ExampleProductData.ExampleXString) mustNot be (JObject(Nil))
    }
    
    "Deserialization of XJSON succeeds even when information is missing" in {
      ExampleProductData.ExampleXJSON.isInstanceOf[blueeyes.json.xschema.XJSON.type] must be (true)
    }
    "Serialization of XJSON has non-zero information content" in {
      Decomposers.XJSONDecomposer.decompose(ExampleProductData.ExampleXJSON) mustNot be (JObject(Nil))
    }
    
    "Deserialization of XDate succeeds even when information is missing" in {
      ExampleProductData.ExampleXDate.isInstanceOf[blueeyes.json.xschema.XDate.type] must be (true)
    }
    "Serialization of XDate has non-zero information content" in {
      Decomposers.XDateDecomposer.decompose(ExampleProductData.ExampleXDate) mustNot be (JObject(Nil))
    }
    
    "Deserialization of XList succeeds even when information is missing" in {
      ExampleProductData.ExampleXList.isInstanceOf[blueeyes.json.xschema.XList] must be (true)
    }
    "Serialization of XList has non-zero information content" in {
      ExampleProductData.ExampleXList.serialize mustNot be (JObject(Nil))
    }
  
    
    "Deserialization of XSet succeeds even when information is missing" in {
      ExampleProductData.ExampleXSet.isInstanceOf[blueeyes.json.xschema.XSet] must be (true)
    }
    "Serialization of XSet has non-zero information content" in {
      ExampleProductData.ExampleXSet.serialize mustNot be (JObject(Nil))
    }
  
    
    "Deserialization of XArray succeeds even when information is missing" in {
      ExampleProductData.ExampleXArray.isInstanceOf[blueeyes.json.xschema.XArray] must be (true)
    }
    "Serialization of XArray has non-zero information content" in {
      ExampleProductData.ExampleXArray.serialize mustNot be (JObject(Nil))
    }
  
    
    "Deserialization of XMap succeeds even when information is missing" in {
      ExampleProductData.ExampleXMap.isInstanceOf[blueeyes.json.xschema.XMap] must be (true)
    }
    "Serialization of XMap has non-zero information content" in {
      ExampleProductData.ExampleXMap.serialize mustNot be (JObject(Nil))
    }
  
    
    "Deserialization of XOptional succeeds even when information is missing" in {
      ExampleProductData.ExampleXOptional.isInstanceOf[blueeyes.json.xschema.XOptional] must be (true)
    }
    "Serialization of XOptional has non-zero information content" in {
      ExampleProductData.ExampleXOptional.serialize mustNot be (JObject(Nil))
    }
  
    
    "Deserialization of XTuple succeeds even when information is missing" in {
      ExampleProductData.ExampleXTuple.isInstanceOf[blueeyes.json.xschema.XTuple] must be (true)
    }
    "Serialization of XTuple has non-zero information content" in {
      ExampleProductData.ExampleXTuple.serialize mustNot be (JObject(Nil))
    }
  
    
    "Deserialization of XProduct succeeds even when information is missing" in {
      ExampleProductData.ExampleXProduct.isInstanceOf[blueeyes.json.xschema.XProduct] must be (true)
    }
    "Serialization of XProduct has non-zero information content" in {
      ExampleProductData.ExampleXProduct.serialize mustNot be (JObject(Nil))
    }
  
    
    "Deserialization of XCoproduct succeeds even when information is missing" in {
      ExampleProductData.ExampleXCoproduct.isInstanceOf[blueeyes.json.xschema.XCoproduct] must be (true)
    }
    "Serialization of XCoproduct has non-zero information content" in {
      ExampleProductData.ExampleXCoproduct.serialize mustNot be (JObject(Nil))
    }
  
    
    "Deserialization of XUnion succeeds even when information is missing" in {
      ExampleProductData.ExampleXUnion.isInstanceOf[blueeyes.json.xschema.XUnion] must be (true)
    }
    "Serialization of XUnion has non-zero information content" in {
      ExampleProductData.ExampleXUnion.serialize mustNot be (JObject(Nil))
    }
  
    
    "Deserialization of XConstant succeeds even when information is missing" in {
      ExampleProductData.ExampleXConstant.isInstanceOf[blueeyes.json.xschema.XConstant] must be (true)
    }
    "Serialization of XConstant has non-zero information content" in {
      ExampleProductData.ExampleXConstant.serialize mustNot be (JObject(Nil))
    }
  
    
    "Deserialization of XRealField succeeds even when information is missing" in {
      ExampleProductData.ExampleXRealField.isInstanceOf[blueeyes.json.xschema.XRealField] must be (true)
    }
    "Serialization of XRealField has non-zero information content" in {
      ExampleProductData.ExampleXRealField.serialize mustNot be (JObject(Nil))
    }
  
    
    "Deserialization of XViewField succeeds even when information is missing" in {
      ExampleProductData.ExampleXViewField.isInstanceOf[blueeyes.json.xschema.XViewField] must be (true)
    }
    "Serialization of XViewField has non-zero information content" in {
      ExampleProductData.ExampleXViewField.serialize mustNot be (JObject(Nil))
    }
  
    
    "Deserialization of XConstantField succeeds even when information is missing" in {
      ExampleProductData.ExampleXConstantField.isInstanceOf[blueeyes.json.xschema.XConstantField] must be (true)
    }
    "Serialization of XConstantField has non-zero information content" in {
      ExampleProductData.ExampleXConstantField.serialize mustNot be (JObject(Nil))
    }
  
    
    "Deserialization of XOrderAscending succeeds even when information is missing" in {
      ExampleProductData.ExampleXOrderAscending.isInstanceOf[blueeyes.json.xschema.XOrderAscending.type] must be (true)
    }
    "Serialization of XOrderAscending has non-zero information content" in {
      Decomposers.XOrderAscendingDecomposer.decompose(ExampleProductData.ExampleXOrderAscending) mustNot be (JObject(Nil))
    }
    
    "Deserialization of XOrderDescending succeeds even when information is missing" in {
      ExampleProductData.ExampleXOrderDescending.isInstanceOf[blueeyes.json.xschema.XOrderDescending.type] must be (true)
    }
    "Serialization of XOrderDescending has non-zero information content" in {
      Decomposers.XOrderDescendingDecomposer.decompose(ExampleProductData.ExampleXOrderDescending) mustNot be (JObject(Nil))
    }
    
    "Deserialization of XOrderIgnore succeeds even when information is missing" in {
      ExampleProductData.ExampleXOrderIgnore.isInstanceOf[blueeyes.json.xschema.XOrderIgnore.type] must be (true)
    }
    "Serialization of XOrderIgnore has non-zero information content" in {
      Decomposers.XOrderIgnoreDecomposer.decompose(ExampleProductData.ExampleXOrderIgnore) mustNot be (JObject(Nil))
    }
  }
  object ExampleMultitypeData {
    lazy val ExampleXSchema: blueeyes.json.xschema.XSchema = JObject(Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXProduct: blueeyes.json.xschema.XSchema = JObject(JField("XProduct", blueeyes.json.xschema.Decomposers.XProductDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXProduct)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXCoproduct: blueeyes.json.xschema.XSchema = JObject(JField("XCoproduct", blueeyes.json.xschema.Decomposers.XCoproductDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXCoproduct)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXUnion: blueeyes.json.xschema.XSchema = JObject(JField("XUnion", blueeyes.json.xschema.Decomposers.XUnionDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXUnion)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXBoolean: blueeyes.json.xschema.XSchema = JObject(JField("XBoolean", blueeyes.json.xschema.Decomposers.XBooleanDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXBoolean)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXInt: blueeyes.json.xschema.XSchema = JObject(JField("XInt", blueeyes.json.xschema.Decomposers.XIntDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXInt)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXLong: blueeyes.json.xschema.XSchema = JObject(JField("XLong", blueeyes.json.xschema.Decomposers.XLongDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXLong)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXFloat: blueeyes.json.xschema.XSchema = JObject(JField("XFloat", blueeyes.json.xschema.Decomposers.XFloatDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXFloat)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXDouble: blueeyes.json.xschema.XSchema = JObject(JField("XDouble", blueeyes.json.xschema.Decomposers.XDoubleDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXDouble)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXString: blueeyes.json.xschema.XSchema = JObject(JField("XString", blueeyes.json.xschema.Decomposers.XStringDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXString)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXJSON: blueeyes.json.xschema.XSchema = JObject(JField("XJSON", blueeyes.json.xschema.Decomposers.XJSONDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXJSON)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXDate: blueeyes.json.xschema.XSchema = JObject(JField("XDate", blueeyes.json.xschema.Decomposers.XDateDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXDate)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXList: blueeyes.json.xschema.XSchema = JObject(JField("XList", blueeyes.json.xschema.Decomposers.XListDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXList)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXSet: blueeyes.json.xschema.XSchema = JObject(JField("XSet", blueeyes.json.xschema.Decomposers.XSetDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXSet)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXArray: blueeyes.json.xschema.XSchema = JObject(JField("XArray", blueeyes.json.xschema.Decomposers.XArrayDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXArray)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXMap: blueeyes.json.xschema.XSchema = JObject(JField("XMap", blueeyes.json.xschema.Decomposers.XMapDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXMap)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXOptional: blueeyes.json.xschema.XSchema = JObject(JField("XOptional", blueeyes.json.xschema.Decomposers.XOptionalDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXOptional)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXTuple: blueeyes.json.xschema.XSchema = JObject(JField("XTuple", blueeyes.json.xschema.Decomposers.XTupleDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXTuple)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXDefinitionRef: blueeyes.json.xschema.XSchema = JObject(JField("XDefinitionRef", blueeyes.json.xschema.Decomposers.XDefinitionRefDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXDefinitionRef)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXRealField: blueeyes.json.xschema.XSchema = JObject(JField("XRealField", blueeyes.json.xschema.Decomposers.XRealFieldDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXRealField)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXViewField: blueeyes.json.xschema.XSchema = JObject(JField("XViewField", blueeyes.json.xschema.Decomposers.XViewFieldDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXViewField)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXConstantField: blueeyes.json.xschema.XSchema = JObject(JField("XConstantField", blueeyes.json.xschema.Decomposers.XConstantFieldDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXConstantField)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    lazy val ExampleXSchemaFromXConstant: blueeyes.json.xschema.XSchema = JObject(JField("XConstant", blueeyes.json.xschema.Decomposers.XConstantDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXConstant)) :: Nil).deserialize[blueeyes.json.xschema.XSchema]
    
    lazy val ExampleXReference: blueeyes.json.xschema.XReference = JObject(Nil).deserialize[blueeyes.json.xschema.XReference]
    lazy val ExampleXReferenceFromXBoolean: blueeyes.json.xschema.XReference = JObject(JField("XBoolean", blueeyes.json.xschema.Decomposers.XBooleanDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXBoolean)) :: Nil).deserialize[blueeyes.json.xschema.XReference]
    lazy val ExampleXReferenceFromXInt: blueeyes.json.xschema.XReference = JObject(JField("XInt", blueeyes.json.xschema.Decomposers.XIntDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXInt)) :: Nil).deserialize[blueeyes.json.xschema.XReference]
    lazy val ExampleXReferenceFromXLong: blueeyes.json.xschema.XReference = JObject(JField("XLong", blueeyes.json.xschema.Decomposers.XLongDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXLong)) :: Nil).deserialize[blueeyes.json.xschema.XReference]
    lazy val ExampleXReferenceFromXFloat: blueeyes.json.xschema.XReference = JObject(JField("XFloat", blueeyes.json.xschema.Decomposers.XFloatDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXFloat)) :: Nil).deserialize[blueeyes.json.xschema.XReference]
    lazy val ExampleXReferenceFromXDouble: blueeyes.json.xschema.XReference = JObject(JField("XDouble", blueeyes.json.xschema.Decomposers.XDoubleDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXDouble)) :: Nil).deserialize[blueeyes.json.xschema.XReference]
    lazy val ExampleXReferenceFromXString: blueeyes.json.xschema.XReference = JObject(JField("XString", blueeyes.json.xschema.Decomposers.XStringDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXString)) :: Nil).deserialize[blueeyes.json.xschema.XReference]
    lazy val ExampleXReferenceFromXJSON: blueeyes.json.xschema.XReference = JObject(JField("XJSON", blueeyes.json.xschema.Decomposers.XJSONDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXJSON)) :: Nil).deserialize[blueeyes.json.xschema.XReference]
    lazy val ExampleXReferenceFromXDate: blueeyes.json.xschema.XReference = JObject(JField("XDate", blueeyes.json.xschema.Decomposers.XDateDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXDate)) :: Nil).deserialize[blueeyes.json.xschema.XReference]
    lazy val ExampleXReferenceFromXList: blueeyes.json.xschema.XReference = JObject(JField("XList", blueeyes.json.xschema.Decomposers.XListDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXList)) :: Nil).deserialize[blueeyes.json.xschema.XReference]
    lazy val ExampleXReferenceFromXSet: blueeyes.json.xschema.XReference = JObject(JField("XSet", blueeyes.json.xschema.Decomposers.XSetDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXSet)) :: Nil).deserialize[blueeyes.json.xschema.XReference]
    lazy val ExampleXReferenceFromXArray: blueeyes.json.xschema.XReference = JObject(JField("XArray", blueeyes.json.xschema.Decomposers.XArrayDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXArray)) :: Nil).deserialize[blueeyes.json.xschema.XReference]
    lazy val ExampleXReferenceFromXMap: blueeyes.json.xschema.XReference = JObject(JField("XMap", blueeyes.json.xschema.Decomposers.XMapDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXMap)) :: Nil).deserialize[blueeyes.json.xschema.XReference]
    lazy val ExampleXReferenceFromXOptional: blueeyes.json.xschema.XReference = JObject(JField("XOptional", blueeyes.json.xschema.Decomposers.XOptionalDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXOptional)) :: Nil).deserialize[blueeyes.json.xschema.XReference]
    lazy val ExampleXReferenceFromXTuple: blueeyes.json.xschema.XReference = JObject(JField("XTuple", blueeyes.json.xschema.Decomposers.XTupleDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXTuple)) :: Nil).deserialize[blueeyes.json.xschema.XReference]
    lazy val ExampleXReferenceFromXDefinitionRef: blueeyes.json.xschema.XReference = JObject(JField("XDefinitionRef", blueeyes.json.xschema.Decomposers.XDefinitionRefDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXDefinitionRef)) :: Nil).deserialize[blueeyes.json.xschema.XReference]
    
    lazy val ExampleXPrimitiveRef: blueeyes.json.xschema.XPrimitiveRef = JObject(Nil).deserialize[blueeyes.json.xschema.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXBoolean: blueeyes.json.xschema.XPrimitiveRef = JObject(JField("XBoolean", blueeyes.json.xschema.Decomposers.XBooleanDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXBoolean)) :: Nil).deserialize[blueeyes.json.xschema.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXInt: blueeyes.json.xschema.XPrimitiveRef = JObject(JField("XInt", blueeyes.json.xschema.Decomposers.XIntDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXInt)) :: Nil).deserialize[blueeyes.json.xschema.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXLong: blueeyes.json.xschema.XPrimitiveRef = JObject(JField("XLong", blueeyes.json.xschema.Decomposers.XLongDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXLong)) :: Nil).deserialize[blueeyes.json.xschema.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXFloat: blueeyes.json.xschema.XPrimitiveRef = JObject(JField("XFloat", blueeyes.json.xschema.Decomposers.XFloatDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXFloat)) :: Nil).deserialize[blueeyes.json.xschema.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXDouble: blueeyes.json.xschema.XPrimitiveRef = JObject(JField("XDouble", blueeyes.json.xschema.Decomposers.XDoubleDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXDouble)) :: Nil).deserialize[blueeyes.json.xschema.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXString: blueeyes.json.xschema.XPrimitiveRef = JObject(JField("XString", blueeyes.json.xschema.Decomposers.XStringDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXString)) :: Nil).deserialize[blueeyes.json.xschema.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXJSON: blueeyes.json.xschema.XPrimitiveRef = JObject(JField("XJSON", blueeyes.json.xschema.Decomposers.XJSONDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXJSON)) :: Nil).deserialize[blueeyes.json.xschema.XPrimitiveRef]
    lazy val ExampleXPrimitiveRefFromXDate: blueeyes.json.xschema.XPrimitiveRef = JObject(JField("XDate", blueeyes.json.xschema.Decomposers.XDateDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXDate)) :: Nil).deserialize[blueeyes.json.xschema.XPrimitiveRef]
    
    lazy val ExampleXContainerRef: blueeyes.json.xschema.XContainerRef = JObject(Nil).deserialize[blueeyes.json.xschema.XContainerRef]
    lazy val ExampleXContainerRefFromXList: blueeyes.json.xschema.XContainerRef = JObject(JField("XList", blueeyes.json.xschema.Decomposers.XListDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXList)) :: Nil).deserialize[blueeyes.json.xschema.XContainerRef]
    lazy val ExampleXContainerRefFromXSet: blueeyes.json.xschema.XContainerRef = JObject(JField("XSet", blueeyes.json.xschema.Decomposers.XSetDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXSet)) :: Nil).deserialize[blueeyes.json.xschema.XContainerRef]
    lazy val ExampleXContainerRefFromXArray: blueeyes.json.xschema.XContainerRef = JObject(JField("XArray", blueeyes.json.xschema.Decomposers.XArrayDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXArray)) :: Nil).deserialize[blueeyes.json.xschema.XContainerRef]
    lazy val ExampleXContainerRefFromXMap: blueeyes.json.xschema.XContainerRef = JObject(JField("XMap", blueeyes.json.xschema.Decomposers.XMapDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXMap)) :: Nil).deserialize[blueeyes.json.xschema.XContainerRef]
    lazy val ExampleXContainerRefFromXOptional: blueeyes.json.xschema.XContainerRef = JObject(JField("XOptional", blueeyes.json.xschema.Decomposers.XOptionalDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXOptional)) :: Nil).deserialize[blueeyes.json.xschema.XContainerRef]
    lazy val ExampleXContainerRefFromXTuple: blueeyes.json.xschema.XContainerRef = JObject(JField("XTuple", blueeyes.json.xschema.Decomposers.XTupleDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXTuple)) :: Nil).deserialize[blueeyes.json.xschema.XContainerRef]
    
    lazy val ExampleXCollection: blueeyes.json.xschema.XCollection = JObject(Nil).deserialize[blueeyes.json.xschema.XCollection]
    lazy val ExampleXCollectionFromXList: blueeyes.json.xschema.XCollection = JObject(JField("XList", blueeyes.json.xschema.Decomposers.XListDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXList)) :: Nil).deserialize[blueeyes.json.xschema.XCollection]
    lazy val ExampleXCollectionFromXSet: blueeyes.json.xschema.XCollection = JObject(JField("XSet", blueeyes.json.xschema.Decomposers.XSetDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXSet)) :: Nil).deserialize[blueeyes.json.xschema.XCollection]
    lazy val ExampleXCollectionFromXArray: blueeyes.json.xschema.XCollection = JObject(JField("XArray", blueeyes.json.xschema.Decomposers.XArrayDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXArray)) :: Nil).deserialize[blueeyes.json.xschema.XCollection]
    
    lazy val ExampleXDefinition: blueeyes.json.xschema.XDefinition = JObject(Nil).deserialize[blueeyes.json.xschema.XDefinition]
    lazy val ExampleXDefinitionFromXProduct: blueeyes.json.xschema.XDefinition = JObject(JField("XProduct", blueeyes.json.xschema.Decomposers.XProductDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXProduct)) :: Nil).deserialize[blueeyes.json.xschema.XDefinition]
    lazy val ExampleXDefinitionFromXCoproduct: blueeyes.json.xschema.XDefinition = JObject(JField("XCoproduct", blueeyes.json.xschema.Decomposers.XCoproductDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXCoproduct)) :: Nil).deserialize[blueeyes.json.xschema.XDefinition]
    lazy val ExampleXDefinitionFromXUnion: blueeyes.json.xschema.XDefinition = JObject(JField("XUnion", blueeyes.json.xschema.Decomposers.XUnionDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXUnion)) :: Nil).deserialize[blueeyes.json.xschema.XDefinition]
    
    lazy val ExampleXMultitype: blueeyes.json.xschema.XMultitype = JObject(Nil).deserialize[blueeyes.json.xschema.XMultitype]
    lazy val ExampleXMultitypeFromXCoproduct: blueeyes.json.xschema.XMultitype = JObject(JField("XCoproduct", blueeyes.json.xschema.Decomposers.XCoproductDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXCoproduct)) :: Nil).deserialize[blueeyes.json.xschema.XMultitype]
    lazy val ExampleXMultitypeFromXUnion: blueeyes.json.xschema.XMultitype = JObject(JField("XUnion", blueeyes.json.xschema.Decomposers.XUnionDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXUnion)) :: Nil).deserialize[blueeyes.json.xschema.XMultitype]
    
    lazy val ExampleXField: blueeyes.json.xschema.XField = JObject(Nil).deserialize[blueeyes.json.xschema.XField]
    lazy val ExampleXFieldFromXRealField: blueeyes.json.xschema.XField = JObject(JField("XRealField", blueeyes.json.xschema.Decomposers.XRealFieldDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXRealField)) :: Nil).deserialize[blueeyes.json.xschema.XField]
    lazy val ExampleXFieldFromXViewField: blueeyes.json.xschema.XField = JObject(JField("XViewField", blueeyes.json.xschema.Decomposers.XViewFieldDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXViewField)) :: Nil).deserialize[blueeyes.json.xschema.XField]
    lazy val ExampleXFieldFromXConstantField: blueeyes.json.xschema.XField = JObject(JField("XConstantField", blueeyes.json.xschema.Decomposers.XConstantFieldDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXConstantField)) :: Nil).deserialize[blueeyes.json.xschema.XField]
    
    lazy val ExampleXOrder: blueeyes.json.xschema.XOrder = JObject(Nil).deserialize[blueeyes.json.xschema.XOrder]
    lazy val ExampleXOrderFromXOrderAscending: blueeyes.json.xschema.XOrder = JObject(JField("XOrderAscending", blueeyes.json.xschema.Decomposers.XOrderAscendingDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXOrderAscending)) :: Nil).deserialize[blueeyes.json.xschema.XOrder]
    lazy val ExampleXOrderFromXOrderDescending: blueeyes.json.xschema.XOrder = JObject(JField("XOrderDescending", blueeyes.json.xschema.Decomposers.XOrderDescendingDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXOrderDescending)) :: Nil).deserialize[blueeyes.json.xschema.XOrder]
    lazy val ExampleXOrderFromXOrderIgnore: blueeyes.json.xschema.XOrder = JObject(JField("XOrderIgnore", blueeyes.json.xschema.Decomposers.XOrderIgnoreDecomposer.decompose(blueeyes.json.xschema.ExampleProductData.ExampleXOrderIgnore)) :: Nil).deserialize[blueeyes.json.xschema.XOrder]
  }
  class DataCoproductSerializationTest extends Runner(DataCoproductSerializationExamples) with JUnit
  object DataCoproductSerializationExamples extends Specification {
    "Deserialization of XSchema succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXSchema.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchema.serialize mustNot be (JObject(Nil))
    }
  
    "Deserialization of XSchema (from XProduct) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXProduct.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XProduct) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXProduct.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XCoproduct) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXCoproduct.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XCoproduct) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXCoproduct.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XUnion) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXUnion.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XUnion) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXUnion.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XBoolean) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXBoolean.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XBoolean) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXBoolean.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XInt) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXInt.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XInt) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXInt.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XLong) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXLong.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XLong) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXLong.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XFloat) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXFloat.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XFloat) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXFloat.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XDouble) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXDouble.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XDouble) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXDouble.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XString) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXString.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XString) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXString.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XJSON) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXJSON.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XJSON) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXJSON.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XDate) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXDate.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XDate) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXDate.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XList) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXList.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XList) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXList.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XSet) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXSet.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XSet) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXSet.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XArray) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXArray.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XArray) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXArray.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XMap) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXMap.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XMap) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXMap.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XOptional) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXOptional.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XOptional) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXOptional.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XTuple) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXTuple.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XTuple) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXTuple.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XDefinitionRef) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXDefinitionRef.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XDefinitionRef) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXDefinitionRef.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XRealField) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXRealField.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XRealField) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXRealField.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XViewField) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXViewField.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XViewField) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXViewField.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XConstantField) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXConstantField.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XConstantField) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXConstantField.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XSchema (from XConstant) succeeds" in {
      ExampleMultitypeData.ExampleXSchemaFromXConstant.isInstanceOf[blueeyes.json.xschema.XSchema] must be (true)
    }            
    "Serialization of XSchema (from XConstant) has non-zero information content" in {
      ExampleMultitypeData.ExampleXSchemaFromXConstant.serialize mustNot be (JObject(Nil))
    }
    
    "Deserialization of XReference succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXReference.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference has non-zero information content" in {
      ExampleMultitypeData.ExampleXReference.serialize mustNot be (JObject(Nil))
    }
  
    "Deserialization of XReference (from XBoolean) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXBoolean.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference (from XBoolean) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXBoolean.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XReference (from XInt) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXInt.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference (from XInt) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXInt.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XReference (from XLong) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXLong.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference (from XLong) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXLong.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XReference (from XFloat) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXFloat.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference (from XFloat) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXFloat.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XReference (from XDouble) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXDouble.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference (from XDouble) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXDouble.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XReference (from XString) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXString.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference (from XString) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXString.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XReference (from XJSON) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXJSON.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference (from XJSON) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXJSON.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XReference (from XDate) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXDate.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference (from XDate) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXDate.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XReference (from XList) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXList.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference (from XList) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXList.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XReference (from XSet) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXSet.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference (from XSet) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXSet.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XReference (from XArray) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXArray.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference (from XArray) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXArray.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XReference (from XMap) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXMap.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference (from XMap) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXMap.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XReference (from XOptional) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXOptional.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference (from XOptional) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXOptional.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XReference (from XTuple) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXTuple.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference (from XTuple) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXTuple.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XReference (from XDefinitionRef) succeeds" in {
      ExampleMultitypeData.ExampleXReferenceFromXDefinitionRef.isInstanceOf[blueeyes.json.xschema.XReference] must be (true)
    }            
    "Serialization of XReference (from XDefinitionRef) has non-zero information content" in {
      ExampleMultitypeData.ExampleXReferenceFromXDefinitionRef.serialize mustNot be (JObject(Nil))
    }
    
    "Deserialization of XPrimitiveRef succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXPrimitiveRef.isInstanceOf[blueeyes.json.xschema.XPrimitiveRef] must be (true)
    }            
    "Serialization of XPrimitiveRef has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRef.serialize mustNot be (JObject(Nil))
    }
  
    "Deserialization of XPrimitiveRef (from XBoolean) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXBoolean.isInstanceOf[blueeyes.json.xschema.XPrimitiveRef] must be (true)
    }            
    "Serialization of XPrimitiveRef (from XBoolean) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXBoolean.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XPrimitiveRef (from XInt) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXInt.isInstanceOf[blueeyes.json.xschema.XPrimitiveRef] must be (true)
    }            
    "Serialization of XPrimitiveRef (from XInt) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXInt.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XPrimitiveRef (from XLong) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXLong.isInstanceOf[blueeyes.json.xschema.XPrimitiveRef] must be (true)
    }            
    "Serialization of XPrimitiveRef (from XLong) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXLong.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XPrimitiveRef (from XFloat) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXFloat.isInstanceOf[blueeyes.json.xschema.XPrimitiveRef] must be (true)
    }            
    "Serialization of XPrimitiveRef (from XFloat) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXFloat.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XPrimitiveRef (from XDouble) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXDouble.isInstanceOf[blueeyes.json.xschema.XPrimitiveRef] must be (true)
    }            
    "Serialization of XPrimitiveRef (from XDouble) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXDouble.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XPrimitiveRef (from XString) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXString.isInstanceOf[blueeyes.json.xschema.XPrimitiveRef] must be (true)
    }            
    "Serialization of XPrimitiveRef (from XString) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXString.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XPrimitiveRef (from XJSON) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXJSON.isInstanceOf[blueeyes.json.xschema.XPrimitiveRef] must be (true)
    }            
    "Serialization of XPrimitiveRef (from XJSON) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXJSON.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XPrimitiveRef (from XDate) succeeds" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXDate.isInstanceOf[blueeyes.json.xschema.XPrimitiveRef] must be (true)
    }            
    "Serialization of XPrimitiveRef (from XDate) has non-zero information content" in {
      ExampleMultitypeData.ExampleXPrimitiveRefFromXDate.serialize mustNot be (JObject(Nil))
    }
    
    "Deserialization of XContainerRef succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXContainerRef.isInstanceOf[blueeyes.json.xschema.XContainerRef] must be (true)
    }            
    "Serialization of XContainerRef has non-zero information content" in {
      ExampleMultitypeData.ExampleXContainerRef.serialize mustNot be (JObject(Nil))
    }
  
    "Deserialization of XContainerRef (from XList) succeeds" in {
      ExampleMultitypeData.ExampleXContainerRefFromXList.isInstanceOf[blueeyes.json.xschema.XContainerRef] must be (true)
    }            
    "Serialization of XContainerRef (from XList) has non-zero information content" in {
      ExampleMultitypeData.ExampleXContainerRefFromXList.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XContainerRef (from XSet) succeeds" in {
      ExampleMultitypeData.ExampleXContainerRefFromXSet.isInstanceOf[blueeyes.json.xschema.XContainerRef] must be (true)
    }            
    "Serialization of XContainerRef (from XSet) has non-zero information content" in {
      ExampleMultitypeData.ExampleXContainerRefFromXSet.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XContainerRef (from XArray) succeeds" in {
      ExampleMultitypeData.ExampleXContainerRefFromXArray.isInstanceOf[blueeyes.json.xschema.XContainerRef] must be (true)
    }            
    "Serialization of XContainerRef (from XArray) has non-zero information content" in {
      ExampleMultitypeData.ExampleXContainerRefFromXArray.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XContainerRef (from XMap) succeeds" in {
      ExampleMultitypeData.ExampleXContainerRefFromXMap.isInstanceOf[blueeyes.json.xschema.XContainerRef] must be (true)
    }            
    "Serialization of XContainerRef (from XMap) has non-zero information content" in {
      ExampleMultitypeData.ExampleXContainerRefFromXMap.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XContainerRef (from XOptional) succeeds" in {
      ExampleMultitypeData.ExampleXContainerRefFromXOptional.isInstanceOf[blueeyes.json.xschema.XContainerRef] must be (true)
    }            
    "Serialization of XContainerRef (from XOptional) has non-zero information content" in {
      ExampleMultitypeData.ExampleXContainerRefFromXOptional.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XContainerRef (from XTuple) succeeds" in {
      ExampleMultitypeData.ExampleXContainerRefFromXTuple.isInstanceOf[blueeyes.json.xschema.XContainerRef] must be (true)
    }            
    "Serialization of XContainerRef (from XTuple) has non-zero information content" in {
      ExampleMultitypeData.ExampleXContainerRefFromXTuple.serialize mustNot be (JObject(Nil))
    }
    
    "Deserialization of XCollection succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXCollection.isInstanceOf[blueeyes.json.xschema.XCollection] must be (true)
    }            
    "Serialization of XCollection has non-zero information content" in {
      ExampleMultitypeData.ExampleXCollection.serialize mustNot be (JObject(Nil))
    }
  
    "Deserialization of XCollection (from XList) succeeds" in {
      ExampleMultitypeData.ExampleXCollectionFromXList.isInstanceOf[blueeyes.json.xschema.XCollection] must be (true)
    }            
    "Serialization of XCollection (from XList) has non-zero information content" in {
      ExampleMultitypeData.ExampleXCollectionFromXList.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XCollection (from XSet) succeeds" in {
      ExampleMultitypeData.ExampleXCollectionFromXSet.isInstanceOf[blueeyes.json.xschema.XCollection] must be (true)
    }            
    "Serialization of XCollection (from XSet) has non-zero information content" in {
      ExampleMultitypeData.ExampleXCollectionFromXSet.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XCollection (from XArray) succeeds" in {
      ExampleMultitypeData.ExampleXCollectionFromXArray.isInstanceOf[blueeyes.json.xschema.XCollection] must be (true)
    }            
    "Serialization of XCollection (from XArray) has non-zero information content" in {
      ExampleMultitypeData.ExampleXCollectionFromXArray.serialize mustNot be (JObject(Nil))
    }
    
    "Deserialization of XDefinition succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXDefinition.isInstanceOf[blueeyes.json.xschema.XDefinition] must be (true)
    }            
    "Serialization of XDefinition has non-zero information content" in {
      ExampleMultitypeData.ExampleXDefinition.serialize mustNot be (JObject(Nil))
    }
  
    "Deserialization of XDefinition (from XProduct) succeeds" in {
      ExampleMultitypeData.ExampleXDefinitionFromXProduct.isInstanceOf[blueeyes.json.xschema.XDefinition] must be (true)
    }            
    "Serialization of XDefinition (from XProduct) has non-zero information content" in {
      ExampleMultitypeData.ExampleXDefinitionFromXProduct.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XDefinition (from XCoproduct) succeeds" in {
      ExampleMultitypeData.ExampleXDefinitionFromXCoproduct.isInstanceOf[blueeyes.json.xschema.XDefinition] must be (true)
    }            
    "Serialization of XDefinition (from XCoproduct) has non-zero information content" in {
      ExampleMultitypeData.ExampleXDefinitionFromXCoproduct.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XDefinition (from XUnion) succeeds" in {
      ExampleMultitypeData.ExampleXDefinitionFromXUnion.isInstanceOf[blueeyes.json.xschema.XDefinition] must be (true)
    }            
    "Serialization of XDefinition (from XUnion) has non-zero information content" in {
      ExampleMultitypeData.ExampleXDefinitionFromXUnion.serialize mustNot be (JObject(Nil))
    }
    
    "Deserialization of XMultitype succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXMultitype.isInstanceOf[blueeyes.json.xschema.XMultitype] must be (true)
    }            
    "Serialization of XMultitype has non-zero information content" in {
      ExampleMultitypeData.ExampleXMultitype.serialize mustNot be (JObject(Nil))
    }
  
    "Deserialization of XMultitype (from XCoproduct) succeeds" in {
      ExampleMultitypeData.ExampleXMultitypeFromXCoproduct.isInstanceOf[blueeyes.json.xschema.XMultitype] must be (true)
    }            
    "Serialization of XMultitype (from XCoproduct) has non-zero information content" in {
      ExampleMultitypeData.ExampleXMultitypeFromXCoproduct.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XMultitype (from XUnion) succeeds" in {
      ExampleMultitypeData.ExampleXMultitypeFromXUnion.isInstanceOf[blueeyes.json.xschema.XMultitype] must be (true)
    }            
    "Serialization of XMultitype (from XUnion) has non-zero information content" in {
      ExampleMultitypeData.ExampleXMultitypeFromXUnion.serialize mustNot be (JObject(Nil))
    }
    
    "Deserialization of XField succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXField.isInstanceOf[blueeyes.json.xschema.XField] must be (true)
    }            
    "Serialization of XField has non-zero information content" in {
      ExampleMultitypeData.ExampleXField.serialize mustNot be (JObject(Nil))
    }
  
    "Deserialization of XField (from XRealField) succeeds" in {
      ExampleMultitypeData.ExampleXFieldFromXRealField.isInstanceOf[blueeyes.json.xschema.XField] must be (true)
    }            
    "Serialization of XField (from XRealField) has non-zero information content" in {
      ExampleMultitypeData.ExampleXFieldFromXRealField.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XField (from XViewField) succeeds" in {
      ExampleMultitypeData.ExampleXFieldFromXViewField.isInstanceOf[blueeyes.json.xschema.XField] must be (true)
    }            
    "Serialization of XField (from XViewField) has non-zero information content" in {
      ExampleMultitypeData.ExampleXFieldFromXViewField.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XField (from XConstantField) succeeds" in {
      ExampleMultitypeData.ExampleXFieldFromXConstantField.isInstanceOf[blueeyes.json.xschema.XField] must be (true)
    }            
    "Serialization of XField (from XConstantField) has non-zero information content" in {
      ExampleMultitypeData.ExampleXFieldFromXConstantField.serialize mustNot be (JObject(Nil))
    }
    
    "Deserialization of XOrder succeeds even when information is missing" in {
      ExampleMultitypeData.ExampleXOrder.isInstanceOf[blueeyes.json.xschema.XOrder] must be (true)
    }            
    "Serialization of XOrder has non-zero information content" in {
      ExampleMultitypeData.ExampleXOrder.serialize mustNot be (JObject(Nil))
    }
  
    "Deserialization of XOrder (from XOrderAscending) succeeds" in {
      ExampleMultitypeData.ExampleXOrderFromXOrderAscending.isInstanceOf[blueeyes.json.xschema.XOrder] must be (true)
    }            
    "Serialization of XOrder (from XOrderAscending) has non-zero information content" in {
      ExampleMultitypeData.ExampleXOrderFromXOrderAscending.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XOrder (from XOrderDescending) succeeds" in {
      ExampleMultitypeData.ExampleXOrderFromXOrderDescending.isInstanceOf[blueeyes.json.xschema.XOrder] must be (true)
    }            
    "Serialization of XOrder (from XOrderDescending) has non-zero information content" in {
      ExampleMultitypeData.ExampleXOrderFromXOrderDescending.serialize mustNot be (JObject(Nil))
    }
    "Deserialization of XOrder (from XOrderIgnore) succeeds" in {
      ExampleMultitypeData.ExampleXOrderFromXOrderIgnore.isInstanceOf[blueeyes.json.xschema.XOrder] must be (true)
    }            
    "Serialization of XOrder (from XOrderIgnore) has non-zero information content" in {
      ExampleMultitypeData.ExampleXOrderFromXOrderIgnore.serialize mustNot be (JObject(Nil))
    }
  }
  class DataConstantsSerializationTest extends Runner(DataConstantsSerializationExamples) with JUnit
  object DataConstantsSerializationExamples extends Specification {
    
  }
}