// These tests were auto-generated by Lift Json XSchema - do not edit
package blueeyes.demo {

  import blueeyes.json.JsonParser._
  import blueeyes.json.JsonAST._
  
  import blueeyes.json.xschema.DefaultSerialization._
  
  import blueeyes.demo.Serialization._
  import blueeyes.demo.Constants._
import org.specs2.mutable.Specification
import org.specs2.matcher.MustThrownMatchers

object ExampleProductData {
    lazy val ExampleContact: blueeyes.demo.Contact = JObject(Nil).deserialize[blueeyes.demo.Contact]
  }

  object DataProductSerializationExamples extends Specification  with MustThrownMatchers{
    "Deserialization of Contact succeeds even when information is missing" in {
      ExampleProductData.ExampleContact.isInstanceOf[blueeyes.demo.Contact] must be_==(true)
    }

    "Serialization of Contact has non-zero information content" in {
      ExampleProductData.ExampleContact.serialize must_!=(JObject(Nil))
    }
  }
}
